// <auto-generated />
using System;
using GroupLN.MarketData.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace GroupLN.MarketData.Persistence.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    [Migration("20260626113000_Sprint14_MatchScorePrecision")]
    partial class Sprint14_MatchScorePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeveloperName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GeoMunicipalSectionId")
                        .HasColumnType("int");

                    b.Property<int?>("GeoMunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GeoMunicipalSectionId")
                        .HasDatabaseName("IX_CanonicalProject_GeoMunicipalSectionId");

                    b.HasIndex("GeoMunicipalityId")
                        .HasDatabaseName("IX_CanonicalProject_GeoMunicipalityId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_CanonicalProject_NormalizedName");

                    b.ToTable("CanonicalProject", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalProjectAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CanonicalProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<long>("MarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatchReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProjectId")
                        .HasDatabaseName("IX_CanonicalProjectAsset_CanonicalProjectId");

                    b.HasIndex("IsPrimary")
                        .HasDatabaseName("IX_CanonicalProjectAsset_IsPrimary");

                    b.HasIndex("MarketAssetId")
                        .HasDatabaseName("IX_CanonicalProjectAsset_MarketAssetId");

                    b.HasIndex("CanonicalProjectId", "MarketAssetId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CanonicalProjectAsset_Project_Asset");

                    b.ToTable("CanonicalProjectAsset", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<long>("CanonicalProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConflictSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("HasAreaConflict")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPriceConflict")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStatusConflict")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAmbiguous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("PricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<long>("RepresentativeMarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProjectId")
                        .HasDatabaseName("IX_CanonicalUnit_CanonicalProjectId");

                    b.HasIndex("RepresentativeMarketAssetId")
                        .HasDatabaseName("IX_CanonicalUnit_RepresentativeMarketAssetId");

                    b.ToTable("CanonicalUnit", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalUnitAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CanonicalUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("bit");

                    b.Property<long>("MarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatchReasons")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(7)
                        .HasColumnType("decimal(7,0)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalUnitId")
                        .HasDatabaseName("IX_CanonicalUnitAsset_CanonicalUnitId");

                    b.HasIndex("MarketAssetId")
                        .HasDatabaseName("IX_CanonicalUnitAsset_MarketAssetId");

                    b.HasIndex("CanonicalUnitId", "MarketAssetId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CanonicalUnitAsset_Unit_Asset");

                    b.ToTable("CanonicalUnitAsset", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Errors")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListingsCreated")
                        .HasColumnType("int");

                    b.Property<int>("ListingsFound")
                        .HasColumnType("int");

                    b.Property<int>("ListingsUpdated")
                        .HasColumnType("int");

                    b.Property<string>("LogMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("CrawlerRun", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CrawlFrequencyHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCrawledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CrawlerSource", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://www.immoweb.be",
                            CrawlFrequencyHours = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Immoweb",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://www.zimmo.be",
                            CrawlFrequencyHours = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Name = "Zimmo",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://www.immoscoop.be",
                            CrawlFrequencyHours = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Name = "Immoscoop",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://www.immovlan.be",
                            CrawlFrequencyHours = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Name = "Immovlan",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "https://www.realo.be",
                            CrawlFrequencyHours = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Name = "Realo",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BaseUrl = "https://www.biddit.be",
                            CrawlFrequencyHours = 168,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Name = "Biddit",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BaseUrl = "https://www.immonotaire.be",
                            CrawlFrequencyHours = 168,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Name = "ImmoNotaire",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerSourceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentPhase")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentProgress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAttemptedCrawlAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastFailedCrawlAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastResultErrors")
                        .HasColumnType("int");

                    b.Property<int?>("LastResultFound")
                        .HasColumnType("int");

                    b.Property<int?>("LastResultNew")
                        .HasColumnType("int");

                    b.Property<int?>("LastResultUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSuccessfulCrawlAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextCrawlAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceName")
                        .IsUnique()
                        .HasDatabaseName("UQ_CrawlerSourceStatus_SourceName");

                    b.ToTable("CrawlerSourceStatus", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.GeoMunicipalSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameDutch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameFrench")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameGerman")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NisCodeMunicipality")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PseudoNis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("NisCodeMunicipality")
                        .HasDatabaseName("IX_GeoMunicipalSection_NisCodeMunicipality");

                    b.HasIndex("PseudoNis")
                        .IsUnique()
                        .HasDatabaseName("UQ_GeoMunicipalSection_PseudoNis");

                    b.HasIndex("ZipCode")
                        .HasDatabaseName("IX_GeoMunicipalSection_ZipCode");

                    b.ToTable("GeoMunicipalSection", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.GeoMunicipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameDutch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameFrench")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameGerman")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NisCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NisCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_GeoMunicipality_NisCode");

                    b.ToTable("GeoMunicipality", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.GeocodingCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("BE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AddressKey")
                        .IsUnique();

                    b.ToTable("GeocodingCache", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketAreaStatistics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AverageLivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("AveragePricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MaxLivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("MaxPricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinLivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("MinPricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProjectsTotal")
                        .HasColumnType("int");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoldPercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("UnitsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("UnitsReserved")
                        .HasColumnType("int");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("int");

                    b.Property<int>("UnitsTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AveragePricePerSqm");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("PostalCode", "PropertyType");

                    b.ToTable("MarketAreaStatistics", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("BE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeveloperName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeveloperPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeveloperWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EPCLabel")
                        .HasColumnType("int");

                    b.Property<decimal?>("EPCScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("EnergyFeatures")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstSoldAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<int?>("GarageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("GardenArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("GeoMunicipalSectionId")
                        .HasColumnType("int");

                    b.Property<int?>("GeoMunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProjectGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LandArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("LifecycleConfidence")
                        .HasColumnType("int");

                    b.Property<string>("LifecycleSource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("int");

                    b.Property<string>("LifecycleStatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LifecycleStatusUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("LocationResolutionConfidence")
                        .HasColumnType("int");

                    b.Property<string>("LocationResolutionSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LocationResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<bool>("NewBuild")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentMarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProjectExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PropertySubType")
                        .HasColumnType("int");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int?>("SaleStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ShowerCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Street")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("TerraceArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ToiletCount")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<string>("UnitExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_MarketAsset_AssetKey");

                    b.HasIndex("City");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("GeoMunicipalSectionId")
                        .HasDatabaseName("IX_MarketAsset_GeoMunicipalSectionId");

                    b.HasIndex("GeoMunicipalityId")
                        .HasDatabaseName("IX_MarketAsset_GeoMunicipalityId");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("ParentMarketAssetId")
                        .HasDatabaseName("IX_MarketAsset_ParentMarketAssetId");

                    b.HasIndex("PostalCode");

                    b.HasIndex("ProjectExternalId")
                        .HasDatabaseName("IX_MarketAsset_ProjectExternalId");

                    b.HasIndex("PropertyType");

                    b.HasIndex("TransactionType");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_MarketAsset_Coordinates");

                    b.ToTable("MarketAsset", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketAssetMatchCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CandidateMarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("ComparedFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExistingMarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<string>("MatchLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatchReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("MatchType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateMarketAssetId")
                        .HasDatabaseName("IX_MarketAssetMatchCandidate_CandidateAssetId");

                    b.HasIndex("ExistingMarketAssetId");

                    b.HasIndex("IsConfirmed");

                    b.HasIndex("IsRejected");

                    b.HasIndex("MatchLevel")
                        .HasDatabaseName("IX_MarketAssetMatchCandidate_MatchLevel");

                    b.HasIndex("MatchScore");

                    b.HasIndex("MatchType")
                        .HasDatabaseName("IX_MarketAssetMatchCandidate_MatchType");

                    b.HasIndex("ExistingMarketAssetId", "CandidateMarketAssetId")
                        .HasDatabaseName("IX_MarketAssetMatchCandidate_Pair")
                        .HasFilter("[CandidateMarketAssetId] IS NOT NULL");

                    b.HasIndex("SourceId", "ExternalId")
                        .HasDatabaseName("IX_MarketAssetMatchCandidate_Source_ExternalId");

                    b.ToTable("MarketAssetMatchCandidate", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AskingPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<int>("MissingCrawlCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("SourceId");

                    b.HasIndex("Url");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MarketListing_Source_ExternalId");

                    b.ToTable("MarketListing", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketListingPriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AskingPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MarketListingId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("PriceChangeAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("PriceChangePercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("MarketListingId");

                    b.ToTable("MarketListingPriceHistory", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketListingSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AskingPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("EPCLabel")
                        .HasColumnType("int");

                    b.Property<decimal?>("EPCScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("EnergyFeatures")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<int?>("GarageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("GardenArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsNewBuild")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LandArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("LivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("MarketListingId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("PricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SaleStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ShowerCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TerraceArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ToiletCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketListingId");

                    b.HasIndex("SnapshotDate");

                    b.ToTable("MarketListingSnapshot", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.ProjectAiExtractionCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtractedCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtractedDeveloper")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExtractedHouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExtractedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExtractedNumberOfUnits")
                        .HasColumnType("int");

                    b.Property<string>("ExtractedPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExtractedProjectName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ExtractedStreet")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsMarketingTitle")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectNameConfidence")
                        .HasColumnType("int");

                    b.Property<string>("RawTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InputHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ProjectAiExtractionCache_InputHash");

                    b.HasIndex("SourceName", "ExternalId")
                        .HasDatabaseName("IX_ProjectAiExtractionCache_Source_ExternalId");

                    b.ToTable("ProjectAiExtractionCache", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.ProjectGroupKpi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApartmentCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageLivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("AveragePricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseCount")
                        .HasColumnType("int");

                    b.Property<long>("MarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("MaxLivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("MaxPricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinLivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal?>("MinPricePerSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoldPercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("UnitsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("UnitsReserved")
                        .HasColumnType("int");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("int");

                    b.Property<int>("UnitsTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("SoldPercentage");

                    b.ToTable("ProjectGroupKpi", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.ProjectGroupSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoldPercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("UnitsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("UnitsOption")
                        .HasColumnType("int");

                    b.Property<int>("UnitsReserved")
                        .HasColumnType("int");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("int");

                    b.Property<int>("UnitsTotal")
                        .HasColumnType("int");

                    b.Property<int>("UnitsUnknown")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("SnapshotDate");

                    b.ToTable("ProjectGroupSnapshot", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.ProjectPhotoHash", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ImageOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("MarketAssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("PerceptualHash")
                        .HasColumnType("bigint");

                    b.Property<string>("PerceptualHashVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProjectExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_ProjectPhotoHash_ContentHash");

                    b.HasIndex("MarketAssetId")
                        .HasDatabaseName("IX_ProjectPhotoHash_MarketAssetId");

                    b.HasIndex("NormalizedImageUrl")
                        .HasDatabaseName("IX_ProjectPhotoHash_NormalizedImageUrl");

                    b.HasIndex("PerceptualHash")
                        .HasDatabaseName("IX_ProjectPhotoHash_PerceptualHash");

                    b.HasIndex("SourceName", "ProjectExternalId")
                        .HasDatabaseName("IX_ProjectPhotoHash_Source_ExternalId");

                    b.ToTable("ProjectPhotoHash", (string)null);
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalProject", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.GeoMunicipalSection", "GeoMunicipalSection")
                        .WithMany()
                        .HasForeignKey("GeoMunicipalSectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GroupLN.MarketData.Core.Entities.GeoMunicipality", "GeoMunicipality")
                        .WithMany()
                        .HasForeignKey("GeoMunicipalityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GeoMunicipalSection");

                    b.Navigation("GeoMunicipality");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalProjectAsset", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.CanonicalProject", "CanonicalProject")
                        .WithMany("Assets")
                        .HasForeignKey("CanonicalProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "MarketAsset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProject");

                    b.Navigation("MarketAsset");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalUnit", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.CanonicalProject", "CanonicalProject")
                        .WithMany()
                        .HasForeignKey("CanonicalProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", null)
                        .WithMany()
                        .HasForeignKey("RepresentativeMarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalProject");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalUnitAsset", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.CanonicalUnit", "CanonicalUnit")
                        .WithMany("SourceAssets")
                        .HasForeignKey("CanonicalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "MarketAsset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalUnit");

                    b.Navigation("MarketAsset");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerRun", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.CrawlerSource", "Source")
                        .WithMany("Runs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketAsset", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.GeoMunicipalSection", "GeoMunicipalSection")
                        .WithMany("MarketAssets")
                        .HasForeignKey("GeoMunicipalSectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GroupLN.MarketData.Core.Entities.GeoMunicipality", "GeoMunicipality")
                        .WithMany("MarketAssets")
                        .HasForeignKey("GeoMunicipalityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "ParentAsset")
                        .WithMany("ChildUnits")
                        .HasForeignKey("ParentMarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeoMunicipalSection");

                    b.Navigation("GeoMunicipality");

                    b.Navigation("ParentAsset");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketAssetMatchCandidate", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "ExistingAsset")
                        .WithMany("MatchCandidates")
                        .HasForeignKey("ExistingMarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExistingAsset");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketListing", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "Asset")
                        .WithMany("Listings")
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroupLN.MarketData.Core.Entities.CrawlerSource", "Source")
                        .WithMany("Listings")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketListingPriceHistory", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketListing", "Listing")
                        .WithMany("PriceHistory")
                        .HasForeignKey("MarketListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketListingSnapshot", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketListing", "Listing")
                        .WithMany("Snapshots")
                        .HasForeignKey("MarketListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.ProjectGroupKpi", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.ProjectGroupSnapshot", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.ProjectPhotoHash", b =>
                {
                    b.HasOne("GroupLN.MarketData.Core.Entities.MarketAsset", "MarketAsset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketAsset");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalProject", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CanonicalUnit", b =>
                {
                    b.Navigation("SourceAssets");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerSource", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.GeoMunicipalSection", b =>
                {
                    b.Navigation("MarketAssets");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.GeoMunicipality", b =>
                {
                    b.Navigation("MarketAssets");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketAsset", b =>
                {
                    b.Navigation("ChildUnits");

                    b.Navigation("Listings");

                    b.Navigation("MatchCandidates");
                });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketListing", b =>
                {
                    b.Navigation("PriceHistory");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
