// <auto-generated />
using System;
using GroupLN.MarketData.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupLN.MarketData.Persistence.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    partial class MarketDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.UseIdentityColumns();

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerSource", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("BaseUrl").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<int>("CrawlFrequencyHours").HasColumnType("int");
                b.Property<DateTime?>("LastCrawledAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("CrawlerSource");

                var seedDate = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);
                b.HasData(
                    new { Id = 1, Name = "Immoweb",     BaseUrl = "https://www.immoweb.be",    IsActive = true,  CrawlFrequencyHours = 12,  CreatedAt = seedDate, UpdatedAt = seedDate },
                    new { Id = 2, Name = "Zimmo",       BaseUrl = "https://www.zimmo.be",       IsActive = false, CrawlFrequencyHours = 12,  CreatedAt = seedDate, UpdatedAt = seedDate },
                    new { Id = 3, Name = "Immoscoop",   BaseUrl = "https://www.immoscoop.be",   IsActive = false, CrawlFrequencyHours = 24,  CreatedAt = seedDate, UpdatedAt = seedDate },
                    new { Id = 4, Name = "Immovlan",    BaseUrl = "https://www.immovlan.be",    IsActive = false, CrawlFrequencyHours = 24,  CreatedAt = seedDate, UpdatedAt = seedDate },
                    new { Id = 5, Name = "Realo",       BaseUrl = "https://www.realo.be",       IsActive = false, CrawlFrequencyHours = 24,  CreatedAt = seedDate, UpdatedAt = seedDate },
                    new { Id = 6, Name = "Biddit",      BaseUrl = "https://www.biddit.be",      IsActive = false, CrawlFrequencyHours = 168, CreatedAt = seedDate, UpdatedAt = seedDate },
                    new { Id = 7, Name = "ImmoNotaire", BaseUrl = "https://www.immonotaire.be", IsActive = false, CrawlFrequencyHours = 168, CreatedAt = seedDate, UpdatedAt = seedDate }
                );
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerRun", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                b.Property<int>("SourceId").HasColumnType("int");
                b.Property<DateTime>("StartedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("FinishedAt").HasColumnType("datetime2");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<int>("ListingsFound").HasColumnType("int");
                b.Property<int>("ListingsCreated").HasColumnType("int");
                b.Property<int>("ListingsUpdated").HasColumnType("int");
                b.Property<int>("Errors").HasColumnType("int");
                b.Property<string>("LogMessage").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                b.HasKey("Id");
                b.HasIndex("SourceId");
                b.HasIndex("StartedAt");
                b.HasIndex("Status");
                b.ToTable("CrawlerRun");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketProperty", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                b.Property<int>("SourceId").HasColumnType("int");
                b.Property<string>("ExternalId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Url").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("Title").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("PropertyType").HasColumnType("int");
                b.Property<int>("PropertySubType").HasColumnType("int");
                b.Property<int>("TransactionType").HasColumnType("int");
                b.Property<string>("Country").IsRequired().HasMaxLength(2).HasDefaultValue("BE").HasColumnType("nvarchar(2)");
                b.Property<string>("PostalCode").HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("City").HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("Street").HasMaxLength(250).HasColumnType("nvarchar(250)");
                b.Property<string>("HouseNumber").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<decimal?>("Latitude").HasPrecision(9, 6).HasColumnType("decimal(9,6)");
                b.Property<decimal?>("Longitude").HasPrecision(9, 6).HasColumnType("decimal(9,6)");
                b.Property<DateTime>("FirstSeenAt").HasColumnType("datetime2");
                b.Property<DateTime>("LastSeenAt").HasColumnType("datetime2");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime?>("RemovedAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex(new[] { "SourceId", "ExternalId" }, "UQ_MarketProperty_Source_ExternalId").IsUnique();
                b.HasIndex("PostalCode");
                b.HasIndex("City");
                b.HasIndex("PropertyType");
                b.HasIndex("TransactionType");
                b.HasIndex("IsActive");
                b.HasIndex("FirstSeenAt");
                b.HasIndex("LastSeenAt");
                b.ToTable("MarketProperty");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketPropertySnapshot", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                b.Property<long>("MarketPropertyId").HasColumnType("bigint");
                b.Property<DateTime>("SnapshotDate").HasColumnType("datetime2");
                b.Property<decimal?>("AskingPrice").HasPrecision(14, 2).HasColumnType("decimal(14,2)");
                b.Property<decimal?>("LivingArea").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
                b.Property<decimal?>("LandArea").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
                b.Property<int?>("Bedrooms").HasColumnType("int");
                b.Property<int?>("Bathrooms").HasColumnType("int");
                b.Property<int?>("GarageCount").HasColumnType("int");
                b.Property<int?>("ConstructionYear").HasColumnType("int");
                b.Property<decimal?>("EPCScore").HasPrecision(8, 2).HasColumnType("decimal(8,2)");
                b.Property<int?>("EPCLabel").HasColumnType("int");
                b.Property<bool>("IsNewBuild").HasColumnType("bit");
                b.Property<string>("DescriptionHash").HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<string>("RawJson").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("MarketPropertyId");
                b.HasIndex("SnapshotDate");
                b.ToTable("MarketPropertySnapshot");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketPropertyPriceHistory", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                b.Property<long>("MarketPropertyId").HasColumnType("bigint");
                b.Property<DateTime>("DetectedAt").HasColumnType("datetime2");
                b.Property<decimal>("AskingPrice").HasPrecision(14, 2).HasColumnType("decimal(14,2)");
                b.Property<decimal?>("PreviousPrice").HasPrecision(14, 2).HasColumnType("decimal(14,2)");
                b.Property<decimal?>("PriceChangeAmount").HasPrecision(14, 2).HasColumnType("decimal(14,2)");
                b.Property<decimal?>("PriceChangePercentage").HasPrecision(8, 4).HasColumnType("decimal(8,4)");
                b.HasKey("Id");
                b.HasIndex("MarketPropertyId");
                b.HasIndex("DetectedAt");
                b.ToTable("MarketPropertyPriceHistory");
            });

            // Relaties
            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerRun", b =>
            {
                b.HasOne("GroupLN.MarketData.Core.Entities.CrawlerSource", "Source")
                    .WithMany("Runs")
                    .HasForeignKey("SourceId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Source");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketProperty", b =>
            {
                b.HasOne("GroupLN.MarketData.Core.Entities.CrawlerSource", "Source")
                    .WithMany("Properties")
                    .HasForeignKey("SourceId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Source");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketPropertySnapshot", b =>
            {
                b.HasOne("GroupLN.MarketData.Core.Entities.MarketProperty", "Property")
                    .WithMany("Snapshots")
                    .HasForeignKey("MarketPropertyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Property");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketPropertyPriceHistory", b =>
            {
                b.HasOne("GroupLN.MarketData.Core.Entities.MarketProperty", "Property")
                    .WithMany("PriceHistory")
                    .HasForeignKey("MarketPropertyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Property");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.CrawlerSource", b =>
            {
                b.Navigation("Runs");
                b.Navigation("Properties");
            });

            modelBuilder.Entity("GroupLN.MarketData.Core.Entities.MarketProperty", b =>
            {
                b.Navigation("Snapshots");
                b.Navigation("PriceHistory");
            });
#pragma warning restore 612, 618
        }
    }
}
