// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ABEXIndex
{
    public int Id { get; set; }

    public int Jaar { get; set; }

    public int? Kwartaal { get; set; }

    public decimal IndexWaarde { get; set; }

    public bool IsActief { get; set; }
}
