// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ActivityGroup
{
    public int GroupId { get; set; }

    public string Name { get; set; }

    public decimal? Lot { get; set; }

    public virtual ICollection<Activity> Activity { get; set; } = new List<Activity>();

    public virtual ICollection<PlanningSectie> PlanningSectie { get; set; } = new List<PlanningSectie>();
}