// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;

namespace DALCore.Models;

public partial class ActivityGroup
{
    public int GroupId { get; set; }

    public string Name { get; set; }

    public decimal? Lot { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.GroupId;
        bo.Display = "Deel " + this.Lot + " - " + this.Name;
        bo.Group = System.Convert.ToString(this.Lot);
        return bo;
    }

}