// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class AspnetProfile
{
    public Guid UserId { get; set; }

    public string PropertyNames { get; set; }

    public string PropertyValuesString { get; set; }

    public byte[] PropertyValuesBinary { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public virtual AspnetUsers User { get; set; }
}