// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class AspNetRoles1
{
    public string Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<AspNetUsers1> User { get; set; } = new List<AspNetUsers1>();
}