// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class AspnetRoles
{
    public Guid ApplicationId { get; set; }

    public Guid RoleId { get; set; }

    public string RoleName { get; set; }

    public string LoweredRoleName { get; set; }

    public string Description { get; set; }

    public virtual AspnetApplications Application { get; set; }

    public virtual ICollection<AspnetUsers> User { get; set; } = new List<AspnetUsers>();
}