// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BadWeatherDays
{
    public int Id { get; set; }

    public DateOnly Date { get; set; }

    public int WeatherstationId { get; set; }

    public int Type { get; set; }

    public virtual WheaterStations Weatherstation { get; set; }
}