// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BlogArtikel
{
    public int Id { get; set; }

    public string Titel { get; set; }

    public string Slug { get; set; }

    public string PreviewTekst { get; set; }

    public string DetailTitel { get; set; }

    public string DetailTitelTekst { get; set; }

    public string FotoBestand { get; set; }

    public DateTime Datum { get; set; }

    public bool IsGepubliceerd { get; set; }

    public int SortOrder { get; set; }

    public DateTime AangemaaktOp { get; set; }

    public DateTime GewijzigdOp { get; set; }

    public string MetaTitel { get; set; }

    public string MetaOmschrijving { get; set; }

    public string MetaKeywords { get; set; }

    public string GeoRegio { get; set; }

    public string GeoPlaatsnaam { get; set; }

    public string GeoPositie { get; set; }

    public virtual ICollection<BlogArtikelBlok> Blokken { get; set; } = new List<BlogArtikelBlok>();

    public virtual ICollection<BlogArtikelFaq> FaqItems { get; set; } = new List<BlogArtikelFaq>();
}
