// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BlogArtikelBlok
{
    public int Id { get; set; }

    public int ArtikelId { get; set; }

    public int SortOrder { get; set; }

    public string Titel { get; set; }

    public string RijkeTekst { get; set; }

    public string FotoBestand { get; set; }

    public virtual BlogArtikel Artikel { get; set; }
}
