// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BlogArtikelFaq
{
    public int Id { get; set; }

    public int ArtikelId { get; set; }

    public int SortOrder { get; set; }

    public string Vraag { get; set; }

    public string Antwoord { get; set; }

    public virtual BlogArtikel Artikel { get; set; }
}
