// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetSanitair
{
    public int Id { get; set; }

    public int BudgetVersieId { get; set; }

    public string EenheidNaam { get; set; }

    public int? UnitTypeId { get; set; }

    public int SortOrder { get; set; }

    public int Badkamer { get; set; }

    public int ToiletInBadkamer { get; set; }

    public int AfzonderlijkToilet { get; set; }

    public int DoucheInBadkamer { get; set; }

    public int Douchekamer { get; set; }

    public virtual BudgetVersie BudgetVersie { get; set; }

    public virtual UnitTypes UnitType { get; set; }
}
