// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetGegevens
{
    public int Id { get; set; }

    public int BudgetVersieId { get; set; }

    public string Naam { get; set; }

    public string Adres { get; set; }

    public int? BouwheerCompanyId { get; set; }

    public int AantalLiften { get; set; }

    public int AantalBinnentrappen { get; set; }

    public int AantalBovengrondseVerdiepingen { get; set; }

    public int AantalVerdiepingenOndergronds { get; set; }

    public string TypePoorten { get; set; }

    public string TypeDak { get; set; }

    public int GevelLeienSidings { get; set; }

    public decimal? OppFunderingen { get; set; }

    public decimal? M3Grondwerk { get; set; }

    public decimal? LmBerlinerwanden { get; set; }

    public decimal? LmSecanpalen { get; set; }

    public decimal? M3Onderschoeiingen { get; set; }

    public int? AantalVeluxen { get; set; }

    public int? AantalTrapzalen { get; set; }

    public decimal? NacalcBasisprijs { get; set; }

    public int? NacalcBasisJaar { get; set; }

    public decimal? SIndexStart { get; set; }

    public decimal? SIndexHuidig { get; set; }

    public decimal? IIndexStart { get; set; }

    public decimal? IIndexHuidig { get; set; }

    public decimal? GevelMetselwerkPrijsPerM2 { get; set; }

    public decimal? GipswerkenPrijsPerM2 { get; set; }

    public decimal? TerrasPrijsPerM2 { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual BudgetVersie BudgetVersie { get; set; }

    public virtual CompanyInfo Bouwheer { get; set; }
}
