// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetActivityLijnen
{
    public int Id { get; set; }

    public int BudgetVersieId { get; set; }

    public int ActivityId { get; set; }

    public decimal? NacalcPrijsPerEenheid { get; set; }

    public int? NacalcBronProjectId { get; set; }

    public decimal Correctiefactor { get; set; }

    public decimal? AlternatievePrijsPerEenheid { get; set; }

    public bool IsManueel { get; set; }

    public decimal VerhogingsPerc { get; set; }

    public string Omschrijving { get; set; }

    public virtual BudgetVersie BudgetVersie { get; set; }

    public virtual Activity Activity { get; set; }
}
