// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetVerkoopLijn
{
    public int Id { get; set; }

    public int BudgetVersieId { get; set; }

    public string EenheidNaam { get; set; }

    public int? UnitId { get; set; }

    public int? CodeBouw { get; set; }

    public int? CodeGrond { get; set; }

    public decimal? OppTuin { get; set; }

    public decimal? OppTerras { get; set; }

    public decimal? OppDakterras { get; set; }

    public bool IsRuil { get; set; }

    public decimal? ExtraForfait { get; set; }

    public int SortOrder { get; set; }

    public virtual BudgetVersie BudgetVersie { get; set; }

    public virtual Units Unit { get; set; }
}
