// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetVersie
{
    public int Id { get; set; }

    public int BudgetMasterId { get; set; }

    public int ProjectId { get; set; }

    public int Versienummer { get; set; }

    public string VersieNaam { get; set; }

    public string Status { get; set; }

    public bool IsHuidig { get; set; }

    public string Notitie { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedByUserId { get; set; }

    public virtual BudgetMaster BudgetMaster { get; set; }

    public virtual Project Project { get; set; }

    public virtual BudgetGegevens BudgetGegevens { get; set; }
}
