// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetPrijsReferentie
{
    public int Id { get; set; }

    public int? ProjectId { get; set; }

    public string PrijsType { get; set; }

    public int Code { get; set; }

    public decimal PrijsPerM2 { get; set; }

    public string Omschrijving { get; set; }

    public virtual Project Project { get; set; }
}
