// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetOppervlaktes
{
    public int Id { get; set; }

    public int BudgetVersieId { get; set; }

    public string EenheidNaam { get; set; }

    public int? UnitGroupTypeId { get; set; }

    public int? UnitTypeId { get; set; }

    public int SortOrder { get; set; }

    public decimal BewoonbareOpp { get; set; }

    public decimal Tuin { get; set; }

    public decimal TerrasPrefab { get; set; }

    public decimal TerrasGelijkvloers { get; set; }

    public decimal Dakterras { get; set; }

    public decimal GaragesParkingsBovenGr { get; set; }

    public decimal GarBergOndergronds { get; set; }

    public decimal BergGelijkvloers { get; set; }

    public decimal Carports { get; set; }

    public decimal DoorritGVL { get; set; }

    public decimal Zolder { get; set; }

    public decimal GemeenschappelijkeDelen { get; set; }

    public decimal Wegenis { get; set; }

    public decimal Grondopp { get; set; }

    public virtual BudgetVersie BudgetVersie { get; set; }

    public virtual UnitGroupTypes UnitGroupType { get; set; }

    public virtual UnitTypes UnitType { get; set; }
}
