// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetMaster
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string Naam { get; set; }

    public string Omschrijving { get; set; }

    public bool IsActief { get; set; }

    public bool IsGearchiveerd { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedByUserId { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<BudgetVersie> BudgetVersies { get; set; } = new List<BudgetVersie>();
}
