// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetParams
{
    public int Id { get; set; }

    public int BudgetVersieId { get; set; }

    public decimal ProjectcoordinatiePerc { get; set; }

    public decimal? ArchitectPerc { get; set; }

    public decimal? VeiligheidscoordEPBPerc { get; set; }

    public decimal? VentVerslaggeverForfait { get; set; }

    public decimal? StudieIRPerc { get; set; }

    public decimal? OpmetingSonderingForfait { get; set; }

    public decimal? DecennaleGeslRuwbouwPerc { get; set; }

    public decimal? ABRPlaatsbeschrPerc { get; set; }

    public decimal? InfrastructuurForfait { get; set; }

    public decimal? LiftPrijsPerStuk { get; set; }

    public decimal WetBreynePerc { get; set; }

    public int? WetBreyneMaanden { get; set; }

    public decimal StraightloanGebouwPerc { get; set; }

    public int? StraightloanGebouwMaanden { get; set; }

    public decimal StraightloanGrondPerc { get; set; }

    public int? StraightloanGrondMaanden { get; set; }

    public decimal? AankoopprijsGrond { get; set; }

    public decimal OnvoorzienPerc { get; set; }

    public decimal? PubliciteitForfait { get; set; }

    public virtual BudgetVersie BudgetVersie { get; set; }
}
