// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class BudgetGevelElementen
{
    public int Id { get; set; }

    public int BudgetVersieId { get; set; }

    public string ElementType { get; set; }

    public string EenheidNaam { get; set; }

    public string Beschrijving { get; set; }

    public decimal Aantal { get; set; }

    public decimal? Breedte { get; set; }

    public decimal? Hoogte { get; set; }

    public decimal? Lengte { get; set; }

    public int SortOrder { get; set; }

    public virtual BudgetVersie BudgetVersie { get; set; }
}
