// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ChangeOrderDetail
{
    public int Id { get; set; }

    public int ChangeOrderId { get; set; }

    public string Description { get; set; }

    public int? MeasurementType { get; set; }

    public int? MeasurementUnit { get; set; }

    public int Number { get; set; }

    public decimal Price { get; set; }

    public decimal Commission { get; set; }

    public bool? Invoicable { get; set; }

    public bool? Invoiced { get; set; }

    public virtual ChangeOrder ChangeOrder { get; set; }
}