// <auto-generated> Handmatig toegevoegd, zelfde stijl als de EF Core Power Tools-gegenereerde modellen
// hiernaast (migratie 064_ChangeOrderOffertesEnFacturatieplan.sql). </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

/// <summary>Het facturatieplan van een wijzigingsopdracht (design-handoff 20d, functionele spec §5):
/// de verdeling van het bedrag in voorschot/tussentijds/saldo. Zie ChangeOrderPaymentTermKind/
/// ChangeOrderPaymentTermTrigger in ServiceCore.Helpers voor de betekenis van Kind/TriggerType.</summary>
public partial class ChangeOrderPaymentTerm
{
    public int Id { get; set; }

    public int ChangeOrderId { get; set; }

    public byte Kind { get; set; }

    public decimal? Percentage { get; set; }

    public decimal? FixedAmount { get; set; }

    public byte TriggerType { get; set; }

    public int? TriggerStageId { get; set; }

    public DateTime? ReleasedAt { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ChangeOrder ChangeOrder { get; set; }

    public virtual InvoicingPaymentStages TriggerStage { get; set; }
}
