// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ChangeOrder
{
    public int Id { get; set; }

    public int ClientAccountId { get; set; }

    public string Description { get; set; }

    public DateOnly Date { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public string Comment { get; set; }

    public DateOnly? DateSendToClient { get; set; }

    public DateOnly? DateAgreement { get; set; }

    public bool Invoiceable { get; set; }

    public int ContractActivityId { get; set; }

    public string ChangeOrderConditions { get; set; }

    /// <summary>Offertes & wijzigingen gl-v2 (migratie 064) — een offerte aan de klant en een WO zitten in
    /// dezelfde tabel (geen aparte offerte-tabel): IsQuote=1 is een offerte. "Omzetten" maakt sinds
    /// 2026-10-02 een NIEUWE WO-rij (SourceKind=3, SourceChangeOrderId = de offerte) en vult op de
    /// offerte QuoteConvertedAt; de offerte zelf blijft ongewijzigd bestaan. Oudere rijen werden nog
    /// in-place omgezet (IsQuote=0 mét QuoteConvertedAt). Zie ChangeOrderStatusHelper.</summary>
    public bool IsQuote { get; set; }

    public string QuoteSupplierReference { get; set; }

    public decimal? QuoteVatPercentage { get; set; }

    public DateTime? QuoteConvertedAt { get; set; }

    /// <summary>Migratie 066 (design-handoff 28a) — het originele offertebestand van de leverancier
    /// (opslagnaam in de DocStorage-map "quotes" + de oorspronkelijke bestandsnaam).</summary>
    public string QuoteSourcePath { get; set; }

    public string QuoteSourceFileName { get; set; }

    /// <summary>Migratie 066 (design-handoff 29b "Kopie"/28c "Versie 2") — de ChangeOrder waarvan deze
    /// rij vertrok. Bewust geen navigatie/FK: louter informatief voor de kaart "Bron".</summary>
    public int? SourceChangeOrderId { get; set; }

    /// <summary>1 = kopie (ander lot), 2 = nieuwe versie (vervangt de bron), 3 = wijzigingsopdracht uit een
    /// offerte aan de klant (de bron is dan de offerte-rij, IsQuote=1).</summary>
    public byte? SourceKind { get; set; }

    public virtual ICollection<ChangeOrderDetail> ChangeOrderDetail { get; set; } = new List<ChangeOrderDetail>();

    public virtual ICollection<ChangeOrderPaymentTerm> ChangeOrderPaymentTerm { get; set; } = new List<ChangeOrderPaymentTerm>();

    public virtual ClientAccount ClientAccount { get; set; }

    public virtual ContractActivity ContractActivity { get; set; }

    public virtual ICollection<IncommingInvoiceDetail> IncommingInvoiceDetail { get; set; } = new List<IncommingInvoiceDetail>();
}