// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;

namespace DALCore.Models;

public partial class ChangeOrder
{
    public int Id { get; set; }

    public int ClientAccountId { get; set; }

    public string Description { get; set; }

    public DateOnly Date { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public string Comment { get; set; }

    public DateOnly? DateSendToClient { get; set; }

    public DateOnly? DateAgreement { get; set; }

    public bool Invoiceable { get; set; }

    public int ContractActivityId { get; set; }

    public string ChangeOrderConditions { get; set; }

    public virtual ICollection<ChangeOrderDetail> ChangeOrderDetail { get; set; } = new List<ChangeOrderDetail>();

    public virtual ClientAccount ClientAccount { get; set; }

    public virtual ContractActivity ContractActivity { get; set; }

    public virtual ICollection<IncommingInvoiceDetail> IncommingInvoiceDetail { get; set; } = new List<IncommingInvoiceDetail>();

    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.Id;
        bo.Display = this.Description;
        return bo;
    }

}