// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ChangeOrder
{
    public int Id { get; set; }

    public int ClientAccountId { get; set; }

    public string Description { get; set; }

    public DateOnly Date { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public string Comment { get; set; }

    public DateOnly? DateSendToClient { get; set; }

    public DateOnly? DateAgreement { get; set; }

    public bool Invoiceable { get; set; }

    public int ContractActivityId { get; set; }

    public string ChangeOrderConditions { get; set; }

    /// <summary>Offertes & wijzigingen gl-v2 (design-handoff 20b/20c/20d, migratie 064) — offerte en WO
    /// zijn bewust dezelfde rij (geen aparte offerte-tabel): IsQuote=1 zolang het nog een offerte is,
    /// "Omzetten" zet 'm in-place naar 0 en vult QuoteConvertedAt. Zie ChangeOrderStatusHelper.</summary>
    public bool IsQuote { get; set; }

    public string QuoteSupplierReference { get; set; }

    public decimal? QuoteVatPercentage { get; set; }

    public DateTime? QuoteConvertedAt { get; set; }

    public virtual ICollection<ChangeOrderDetail> ChangeOrderDetail { get; set; } = new List<ChangeOrderDetail>();

    public virtual ICollection<ChangeOrderPaymentTerm> ChangeOrderPaymentTerm { get; set; } = new List<ChangeOrderPaymentTerm>();

    public virtual ClientAccount ClientAccount { get; set; }

    public virtual ContractActivity ContractActivity { get; set; }

    public virtual ICollection<IncommingInvoiceDetail> IncommingInvoiceDetail { get; set; } = new List<IncommingInvoiceDetail>();
}