// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ChangeOrderDetail
{
    public int Id { get; set; }

    public int ChangeOrderId { get; set; }

    public string Description { get; set; }

    public int? MeasurementType { get; set; }

    public int? MeasurementUnit { get; set; }

    public int Number { get; set; }

    public decimal Price { get; set; }

    public decimal Commission { get; set; }

    public bool? Invoicable { get; set; }

    public bool? Invoiced { get; set; }

    public decimal? VatPercentage { get; set; }

    /// <summary>Offertes & wijzigingen gl-v2 (design-handoff 20c, migratie 064) — de goud
    /// "controleer"-vlag: een onzekere OCR-waarde. Een WO met minstens één regel op NeedsReview=1 mag
    /// niet verzonden worden (spec §8).</summary>
    public bool NeedsReview { get; set; }

    /// <summary>Bijgesneden foto uit 20c ("kader rond een foto hangt die aan een regel"), opgeslagen via
    /// dezelfde Storage-service als andere documentbijlagen.</summary>
    public string SourceImagePath { get; set; }

    public virtual ChangeOrder ChangeOrder { get; set; }
}