// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ClientOwnerType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ClientAccount> ClientAccount { get; set; } = new List<ClientAccount>();

    public virtual ICollection<ClientContacts> ClientContacts { get; set; } = new List<ClientContacts>();
}