// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;

namespace DALCore.Models;

public partial class ClientAccount
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Street { get; set; }

    public string Housenumber { get; set; }

    public string Busnumber { get; set; }

    public int? PostalCodeId { get; set; }

    public DateOnly? DateSalesAgreement { get; set; }

    public DateOnly? DateDeedOfSale { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public string DeliveryDoc { get; set; }

    public DateOnly? DeliveryDateDef { get; set; }

    public int? OwnerPercentage { get; set; }

    public int? OwnerTypeId { get; set; }

    public string Salutation { get; set; }

    public string Vatnumber { get; set; }

    public string CompanyName { get; set; }

    public DateOnly? StartDateConstruction { get; set; }

    public int? ExecutionDays { get; set; }

    public string BankAccountNumber { get; set; }

    public bool? InvoiceAddress { get; set; }

    public string InvoiceStreet { get; set; }

    public string InvoiceHousenumber { get; set; }

    public string InvoiceBusnumber { get; set; }

    public int? InvoicePostalCodeId { get; set; }

    public string InvoiceExtra { get; set; }

    public DateOnly? DeedOfSaleExpDate { get; set; }

    public virtual ICollection<ChangeOrder> ChangeOrder { get; set; } = new List<ChangeOrder>();

    public virtual ICollection<ClientContacts> ClientContacts { get; set; } = new List<ClientContacts>();

    public virtual ICollection<ClientGift> ClientGift { get; set; } = new List<ClientGift>();

    public virtual ICollection<ClientPoa> ClientPoa { get; set; } = new List<ClientPoa>();

    public virtual PostalCode InvoicePostalCode { get; set; }

    public virtual ClientOwnerType OwnerType { get; set; }

    public virtual PostalCode PostalCode { get; set; }

    public virtual ICollection<ProjectDocs> ProjectDocs { get; set; } = new List<ProjectDocs>();

    public virtual ICollection<Units> Units { get; set; } = new List<Units>();

    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.Id;
        if (this.CompanyName == "" | this.CompanyName == null)
            bo.Display = this.Name;
        else
            bo.Display = this.CompanyName;
        // bo.Group = Me.
        return bo;
    }

}