// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ClientContactIssuerCompany
{
    public int ClientContactId { get; set; }

    public int IssuerCompanyId { get; set; }

    public int? OctopusRelationId { get; set; }

    public virtual ClientContacts ClientContact { get; set; }

    public virtual IssuerCompany IssuerCompany { get; set; }
}