// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ClientContacts
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Street { get; set; }

    public string Housenumber { get; set; }

    public string Busnumber { get; set; }

    public int? PostalCodeId { get; set; }

    public string Phone { get; set; }

    public string Cellphone { get; set; }

    public string Email { get; set; }

    public bool IsCoOwner { get; set; }

    public decimal? CoOwnerPercentage { get; set; }

    public int? CoOwnerTypeId { get; set; }

    public int ClientAccountId { get; set; }

    public string Forename { get; set; }

    public string Salutation { get; set; }

    public string CompanyName { get; set; }

    public string Vatnumber { get; set; }

    public bool? InvoiceAddress { get; set; }

    public string InvoiceStreet { get; set; }

    public string InvoiceHousenumber { get; set; }

    public string InvoiceBusnumber { get; set; }

    public int? InvoicePostalCodeId { get; set; }

    public virtual ClientAccount ClientAccount { get; set; }

    public virtual ClientOwnerType CoOwnerType { get; set; }

    public virtual PostalCode InvoicePostalCode { get; set; }

    public virtual PostalCode PostalCode { get; set; }
}