// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ClientGift
{
    public int Id { get; set; }

    public int ClientAccountId { get; set; }

    public string Description { get; set; }

    public virtual ClientAccount ClientAccount { get; set; }

    public virtual ICollection<Activity> Activity { get; set; } = new List<Activity>();
}