// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;

namespace DALCore.Models;

public partial class CompanyDepartments
{
    public int DepartmentId { get; set; }

    public string Naam { get; set; }

    public string Straat { get; set; }

    public string Huisnummer { get; set; }

    public string Bus { get; set; }

    public int? PostcodeId { get; set; }

    public string Telefoon { get; set; }

    public string Gsm { get; set; }

    public string Email { get; set; }

    public int CompanyId { get; set; }

    public virtual CompanyInfo Company { get; set; }

    public virtual ICollection<CompanyContacts> CompanyContacts { get; set; } = new List<CompanyContacts>();

    public virtual PostalCode Postcode { get; set; }

    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.DepartmentId;
        bo.Display = this.Naam;
        return bo;
    }

}