// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class CompanyContacts
{
    public int ContactId { get; set; }

    public int CompanyId { get; set; }

    public string ContactNaam { get; set; }

    public string ContactVoornaam { get; set; }

    public string Aanspreking { get; set; }

    public string Functie { get; set; }

    public string Telefoon { get; set; }

    public string Gsm { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public int? DepartmentId { get; set; }

    public virtual CompanyInfo Company { get; set; }

    public virtual CompanyDepartments Department { get; set; }
}