// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;

namespace DALCore.Models;

public partial class CompanyInfo
{
    public int CompanyId { get; set; }

    public string BedrijfsNaam { get; set; }

    public string Straat { get; set; }

    public string Huisnummer { get; set; }

    public string Toevoeging { get; set; }

    public string Busnummer { get; set; }

    public string Telefoon1 { get; set; }

    public string Telefoon2 { get; set; }

    public string Gsm { get; set; }

    public string Fax1 { get; set; }

    public string Fax2 { get; set; }

    public string Email { get; set; }

    public string Weburl { get; set; }

    public string Ondernemingsnummer { get; set; }

    public string RegistratieNr { get; set; }

    public string Bank { get; set; }

    public string Opmerkingen { get; set; }

    public string Documentatie { get; set; }

    public string Type { get; set; }

    public string LandCode { get; set; }

    public int? PostCodeId { get; set; }

    public string Postcode { get; set; }

    public string Gemeente { get; set; }

    public virtual ICollection<CompanyContacts> CompanyContacts { get; set; } = new List<CompanyContacts>();

    public virtual ICollection<CompanyDepartments> CompanyDepartments { get; set; } = new List<CompanyDepartments>();

    public virtual ICollection<Contract> Contract { get; set; } = new List<Contract>();

    public virtual ICollection<IncommingInvoices> IncommingInvoices { get; set; } = new List<IncommingInvoices>();

    public virtual PostalCode PostCode { get; set; }

    public virtual ICollection<Project> ProjectArchitect { get; set; } = new List<Project>();

    public virtual ICollection<Project> ProjectBuilder { get; set; } = new List<Project>();

    public virtual ICollection<Project> ProjectDeveloper { get; set; } = new List<Project>();

    public virtual ICollection<Project> ProjectEngineer { get; set; } = new List<Project>();

    public virtual ICollection<Project> ProjectEpbReporter { get; set; } = new List<Project>();

    public virtual ICollection<Project> ProjectSecurityCoordinator { get; set; } = new List<Project>();

    public virtual ICollection<Activity> Activity { get; set; } = new List<Activity>();

    public virtual ICollection<Project> Project { get; set; } = new List<Project>();

    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.CompanyId;
        bo.Display = this.BedrijfsNaam;

        return bo;
    }
    public SelectBO GetIdNameForSearch()
    {
        SelectBO bo = new SelectBO();
        bo.id  = this.CompanyId;
        bo.text = this.BedrijfsNaam;
        bo.extra = "Company";

        return bo;
    }
}