// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConnectionSettlement
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string PeriodLabel { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual ICollection<ConnectionAdvanceApplication> ConnectionAdvanceApplication { get; set; } = new List<ConnectionAdvanceApplication>();

    public virtual ICollection<ConnectionSettlementSource> ConnectionSettlementSource { get; set; } = new List<ConnectionSettlementSource>();

    public virtual Project Project { get; set; }
}