// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConnectionSettlementSource
{
    public int Id { get; set; }

    public int SettlementId { get; set; }

    public int InvoiceDetailId { get; set; }

    public decimal AmountUsedExcl { get; set; }

    public virtual IncommingInvoiceDetail InvoiceDetail { get; set; }

    public virtual ConnectionSettlement Settlement { get; set; }
}