// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConnectionAdvanceApplication
{
    public int Id { get; set; }

    public int SettlementId { get; set; }

    public int InvoiceLineId { get; set; }

    public decimal AmountUsedExcl { get; set; }

    public virtual InvoicesDetails InvoiceLine { get; set; }

    public virtual ConnectionSettlement Settlement { get; set; }
}