// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConstructionIssueReportItem
{
    public int ReportId { get; set; }

    public int IssueId { get; set; }

    public int Id { get; set; }

    public int? SortOrder { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ConstructionIssue Issue { get; set; }

    public virtual ConstructionIssueReport Report { get; set; }
}