// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConstructionIssueHistory
{
    public int Id { get; set; }

    public int IssueId { get; set; }

    public int Action { get; set; }

    public string UserId { get; set; }

    public DateTime Timestamp { get; set; }

    public string OldValueJson { get; set; }

    public string NewValueJson { get; set; }

    public string Comment { get; set; }

    public virtual ConstructionIssue Issue { get; set; }
}