// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConstructionIssueReport
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int ResponsiblePartyType { get; set; }

    public int? ResponsiblePartyId { get; set; }

    public string ResponsibleOtherName { get; set; }

    public string ResponsibleOtherEmail { get; set; }

    public int ReportType { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedByUserId { get; set; }

    public string FileId { get; set; }

    public virtual ICollection<ConstructionIssueNotification> ConstructionIssueNotification { get; set; } = new List<ConstructionIssueNotification>();

    public virtual ICollection<ConstructionIssueReportItem> ConstructionIssueReportItem { get; set; } = new List<ConstructionIssueReportItem>();

    public virtual Project Project { get; set; }
}