// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConstructionIssue
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int? UnitId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string LocationText { get; set; }

    public int CategoryId { get; set; }

    public int? BuildingPart { get; set; }

    public string RoomOrZone { get; set; }

    public int IssueType { get; set; }

    public int IssuePhase { get; set; }

    public int Priority { get; set; }

    public int Status { get; set; }

    public int ResponsiblePartyType { get; set; }

    public int? ResponsiblePartyId { get; set; }

    public string ResponsibleOtherName { get; set; }

    public string ResponsibleOtherEmail { get; set; }

    public DateOnly? DueDate { get; set; }

    public DateTime? ResolvedDate { get; set; }

    public DateTime? ClosedDate { get; set; }

    public DateTime? LastSentDate { get; set; }

    public string CreatedByUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string LastUpdatedByUserId { get; set; }

    public DateTime? LastUpdatedDate { get; set; }

    public int? PlanDocumentId { get; set; }

    public int? PlanPageNumber { get; set; }

    public decimal? PlanXnormalized { get; set; }

    public decimal? PlanYnormalized { get; set; }

    public bool DoNotAutoNotify { get; set; }

    public DateOnly? PlannedDate { get; set; }

    public virtual ConstructionIssueCategory Category { get; set; }

    public virtual ICollection<ConstructionIssueHistory> ConstructionIssueHistory { get; set; } = new List<ConstructionIssueHistory>();

    public virtual ICollection<ConstructionIssueMedia> ConstructionIssueMedia { get; set; } = new List<ConstructionIssueMedia>();

    public virtual ICollection<ConstructionIssueNotification> ConstructionIssueNotification { get; set; } = new List<ConstructionIssueNotification>();

    public virtual ICollection<ConstructionIssueReportItem> ConstructionIssueReportItem { get; set; } = new List<ConstructionIssueReportItem>();

    public virtual Project Project { get; set; }

    public virtual Units Unit { get; set; }
}