// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConstructionIssueNotification
{
    public int Id { get; set; }

    public int IssueId { get; set; }

    public int RecipientType { get; set; }

    public int? RecipientId { get; set; }

    public string RecipientEmail { get; set; }

    public DateTime SentDate { get; set; }

    public string SentByUserId { get; set; }

    public int Channel { get; set; }

    public int? ReportId { get; set; }

    public bool IsReminder { get; set; }

    public virtual ConstructionIssue Issue { get; set; }

    public virtual ConstructionIssueReport Report { get; set; }
}