// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConstructionIssueMedia
{
    public int Id { get; set; }

    public int IssueId { get; set; }

    public string FileId { get; set; }

    public int MediaType { get; set; }

    public string CreatedByUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ConstructionIssue Issue { get; set; }
}