// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ConstructionIssueCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ConstructionIssue> ConstructionIssue { get; set; } = new List<ConstructionIssue>();
}