// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;

namespace DALCore.Models;

public partial class ContractActivity
{
    public int Id { get; set; }

    public int ContractId { get; set; }

    public int ActivityId { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual ICollection<ChangeOrder> ChangeOrder { get; set; } = new List<ChangeOrder>();

    public virtual Contract Contract { get; set; }

    public virtual ICollection<IncommingInvoiceDetail> IncommingInvoiceDetail { get; set; } = new List<IncommingInvoiceDetail>();

    public virtual Insurances Insurances { get; set; }

    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.Id;
        bo.Display = this.Activity.Omschrijving + " - " + this.Contract.Company.BedrijfsNaam;
        return bo;
    }
}