// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ContactRequests
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string SourceSite { get; set; }

    public string Origin { get; set; }

    public string RequestType { get; set; }

    public int? ProjectId { get; set; }

    public int? UnitId { get; set; }

    public int? DocumentId { get; set; }

    public string DocumentName { get; set; }

    public string DocumentFileName { get; set; }

    public string DocumentType { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Fullname { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Subject { get; set; }

    public string Question { get; set; }

    public virtual ProjectDocs Document { get; set; }

    public virtual Project Project { get; set; }

    public virtual Units Unit { get; set; }
}