// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Country
{
    public string LandIsocode { get; set; }

    public string LandNaam { get; set; }

    public bool Selectable { get; set; }

    public int Id { get; set; }

    public virtual ICollection<PostalCode> PostalCode { get; set; } = new List<PostalCode>();

    public virtual ICollection<Provincie> Provincie { get; set; } = new List<Provincie>();
}