// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace DALCore.Models;

public partial class IncomingInvoiceWarning
{
    public int Id { get; set; }

    public int IncomingInvoiceId { get; set; }

    /// <summary>Gestructureerde code, bv. MissingDueDate, DuplicateSuspected, AmountMismatch.</summary>
    public string WarningCode { get; set; }

    public string WarningMessage { get; set; }

    /// <summary>Info / Warning / Error</summary>
    public string Severity { get; set; }

    /// <summary>Ubl / PdfText / AzureOcr / RuleEngine / DuplicateCheck</summary>
    public string Source { get; set; }

    public bool IsResolved { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual IncommingInvoices IncomingInvoice { get; set; }
}
