// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IncommingInvoices
{
    public int Id { get; set; }

    public DateOnly Date { get; set; }

    public decimal Price { get; set; }

    public int? ContractId { get; set; }

    public string ExternalId { get; set; }

    public int? CompanyId { get; set; }

    public int ProjectId { get; set; }

    public virtual CompanyInfo Company { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual ICollection<IncommingInvoiceDetail> IncommingInvoiceDetail { get; set; } = new List<IncommingInvoiceDetail>();

    public virtual Project Project { get; set; }
}