// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IncomingInvoiceAttachments
{
    public int Id { get; set; }

    public int IncomingInvoiceId { get; set; }

    public string FileName { get; set; }

    public string ContentType { get; set; }

    public string AttachmentType { get; set; }

    public byte[] Content { get; set; }

    public string FilePath { get; set; }

    public long? FileSizeBytes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual IncommingInvoices IncomingInvoice { get; set; }
}