// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IncomingInvoiceWarning
{
    public int Id { get; set; }

    public int IncomingInvoiceId { get; set; }

    public string WarningCode { get; set; }

    public string WarningMessage { get; set; }

    public string Severity { get; set; }

    public string Source { get; set; }

    public bool IsResolved { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual IncommingInvoices IncomingInvoice { get; set; }
}