// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IncomingInvoiceEnrichment
{
    public int Id { get; set; }

    public int IncomingInvoiceId { get; set; }

    public DateTime EnrichedAt { get; set; }

    public string DocumentClassification { get; set; }

    public string SupplierMatchConfidence { get; set; }

    public string SupplierMatchReason { get; set; }

    public string SupplierIban { get; set; }

    public int? SuggestedProjectId { get; set; }

    public string SuggestedProjectName { get; set; }

    public int SuggestedProjectScore { get; set; }

    public string SuggestedProjectConfidence { get; set; }

    public string SuggestedProjectMatchReason { get; set; }

    public string SuggestedProjectMatchedFields { get; set; }

    public string AltProjectCandidatesJson { get; set; }

    public int? SuggestedContractId { get; set; }

    public string SuggestedContractName { get; set; }

    public int SuggestedContractScore { get; set; }

    public string SuggestedContractConfidence { get; set; }

    public string AltContractCandidatesJson { get; set; }

    public string SuggestedAccountingCode { get; set; }

    public string SuggestedAccountingDescription { get; set; }

    public string SuggestedAccountingSource { get; set; }

    public bool IsGeneralCostSuggested { get; set; }

    public long ReasonFlags { get; set; }

    public bool IsDuplicateSuspected { get; set; }

    public int? DuplicateSuspectInvoiceId { get; set; }

    public string ExtractionResultJson { get; set; }

    public DateTime? UserReviewedAt { get; set; }

    public string UserReviewedBy { get; set; }

    public int? UserConfirmedProjectId { get; set; }

    public int? UserConfirmedContractId { get; set; }

    public string UserConfirmedAccountingCode { get; set; }

    public string UserNotes { get; set; }

    public virtual IncommingInvoices IncomingInvoice { get; set; }

    public virtual Project SuggestedProject { get; set; }

    public virtual Project UserConfirmedProject { get; set; }
}