// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IncommingInvoiceDetail
{
    public int Id { get; set; }

    public int IncommingInvoiceId { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int? ContractActId { get; set; }

    public decimal Type { get; set; }

    public int? ChangeOrderId { get; set; }

    public int? ActId { get; set; }

    public virtual Activity Act { get; set; }

    public virtual ChangeOrder ChangeOrder { get; set; }

    public virtual ContractActivity ContractAct { get; set; }

    public virtual IncommingInvoices IncommingInvoice { get; set; }
}