// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Insurances
{
    public int Id { get; set; }

    public int? InsuranceCompanyId { get; set; }

    public DateOnly? Startdate { get; set; }

    public int? Period { get; set; }

    public int? ExtensionPeriod { get; set; }

    public int? GuaranteePeriod { get; set; }

    public int Type { get; set; }

    public DateOnly? Enddate { get; set; }

    public int ContractActivityId { get; set; }

    public virtual ContractActivity ContractActivity { get; set; }

    public virtual InsuranceCompanies InsuranceCompany { get; set; }
}