// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceDunning
{
    public int Id { get; set; }

    public int InvoiceId { get; set; }

    public byte Level { get; set; }

    public decimal? FeeAmount { get; set; }

    public decimal? InterestPct { get; set; }

    public DateTime SentAt { get; set; }

    public DateTime? NextActionAt { get; set; }

    public string Notes { get; set; }

    public virtual Invoices Invoice { get; set; }
}