// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceSequence
{
    public int Id { get; set; }

    public int SeriesId { get; set; }

    public int FiscalYear { get; set; }

    public int CurrentNumber { get; set; }

    public virtual InvoiceSeries Series { get; set; }
}