// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace DALCore.Models;

/// <summary>
/// Alternatieve namen, adressen of codes voor een project,
/// zodat facturen sneller en betrouwbaarder gematcht kunnen worden.
/// </summary>
public partial class InvoiceProjectAlias
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    /// <summary>De alias-tekst die in factuurtekst kan voorkomen.</summary>
    public string Alias { get; set; }

    /// <summary>Name / Street / Reference / Code / City</summary>
    public string AliasType { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual Project Project { get; set; }
}
