// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceSupplierRule
{
    public int Id { get; set; }

    public int? IssuerCompanyId { get; set; }

    public int? CompanyId { get; set; }

    public string SupplierVatNumber { get; set; }

    public string SupplierNameContains { get; set; }

    public string RuleType { get; set; }

    public int? DefaultProjectId { get; set; }

    public int? DefaultContractId { get; set; }

    public string DefaultAccountingCode { get; set; }

    public string DefaultVatCode { get; set; }

    public bool IsGeneralCost { get; set; }

    public bool RequiresManualReview { get; set; }

    public bool RequiresProject { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual CompanyInfo Company { get; set; }

    public virtual Project DefaultProject { get; set; }

    public virtual IssuerCompany IssuerCompany { get; set; }
}