// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace DALCore.Models;

/// <summary>
/// Door gebruikers opgeslaan regels voor leveranciers:
/// standaard project, rekening, vereiste review, altijd algemene kost, enz.
/// </summary>
public partial class InvoiceSupplierRule
{
    public int Id { get; set; }

    public int? IssuerCompanyId { get; set; }

    public int? CompanyId { get; set; }

    /// <summary>BTW-nummer van de leverancier (alternatief voor CompanyId).</summary>
    public string SupplierVatNumber { get; set; }

    /// <summary>Gedeeltelijke leveranciersnaam voor herkenning als CompanyId ontbreekt.</summary>
    public string SupplierNameContains { get; set; }

    /// <summary>
    /// Type van de regel: DefaultProject, DefaultAccount, AlwaysManualReview,
    /// AlwaysGeneralCost, DefaultVatCode, RequiresProject.
    /// </summary>
    public string RuleType { get; set; }

    public int? DefaultProjectId { get; set; }

    public int? DefaultContractId { get; set; }

    public string DefaultAccountingCode { get; set; }

    public string DefaultVatCode { get; set; }

    public bool IsGeneralCost { get; set; }

    public bool RequiresManualReview { get; set; }

    public bool RequiresProject { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public bool IsActive { get; set; }

    // ── Navigatie ─────────────────────────────────────────────────────────────

    public virtual CompanyInfo Company { get; set; }

    public virtual IssuerCompany IssuerCompany { get; set; }

    public virtual Project DefaultProject { get; set; }
}
