// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceSeries
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public bool IsCreditNote { get; set; }

    public bool IsActive { get; set; }

    public int? IssuerCompanyId { get; set; }

    public virtual ICollection<InvoiceSequence> InvoiceSequence { get; set; } = new List<InvoiceSequence>();

    public virtual ICollection<Invoices> Invoices { get; set; } = new List<Invoices>();

    public virtual IssuerCompany IssuerCompany { get; set; }
}