// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;

namespace DALCore.Models;

public partial class InvoicingPaymentGroup
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int ProjectId { get; set; }

    public decimal? VatPercentage { get; set; }

    public virtual ICollection<InvoicingPaymentStages> InvoicingPaymentStages { get; set; } = new List<InvoicingPaymentStages>();

    public virtual Project Project { get; set; }

    public virtual ICollection<UnitConstructionValue> UnitConstructionValue { get; set; } = new List<UnitConstructionValue>();

    public virtual ICollection<Units> Units { get; set; } = new List<Units>();

    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.Id;
        bo.Display = this.Name;
        return bo;
    }

}