// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceProjectAlias
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string Alias { get; set; }

    public string AliasType { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual Project Project { get; set; }
}