// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceAttachments
{
    public int Id { get; set; }

    public int InvoiceId { get; set; }

    public string FileName { get; set; }

    public string MimeType { get; set; }

    public string BlobPath { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Invoices Invoice { get; set; }
}