// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Invoices
{
    public int Id { get; set; }

    public string Filename { get; set; }

    public DateOnly Date { get; set; }

    public int ClientId { get; set; }

    public int ClientType { get; set; }

    public string PublicId { get; set; }

    public DateOnly? ExpirationDate { get; set; }

    public string VatNumber { get; set; }

    public string ClientName { get; set; }

    public string Adress { get; set; }

    public int? PostalCodeId { get; set; }

    public string BankAccount { get; set; }

    public string ExtraInfo { get; set; }

    public string Text { get; set; }

    public string DetailText { get; set; }

    public int? CompanyId { get; set; }

    public virtual ICollection<InvoicesDetails> InvoicesDetails { get; set; } = new List<InvoicesDetails>();

    public virtual PostalCode PostalCode { get; set; }

    public virtual ICollection<Units> Units { get; set; } = new List<Units>();
}