// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceEmailLog
{
    public int Id { get; set; }

    public int InvoiceId { get; set; }

    public string ToAddress { get; set; }

    public string CcAddress { get; set; }

    public string Subject { get; set; }

    public string ProviderId { get; set; }

    public DateTime SentAt { get; set; }

    public string Status { get; set; }

    public virtual Invoices Invoice { get; set; }
}