// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoicePdfArchive
{
    public int Id { get; set; }

    public int InvoiceId { get; set; }

    public byte[] Pdf { get; set; }

    public DateTime GeneratedAt { get; set; }

    public string Sha256 { get; set; }

    public virtual Invoices Invoice { get; set; }
}