// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoicingPaymentStages
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Percentage { get; set; }

    public bool? Invoicable { get; set; }

    public int GroupId { get; set; }

    public int? DocId { get; set; }

    public decimal VatPercentage { get; set; }

    public virtual ProjectDocs Doc { get; set; }

    public virtual InvoicingPaymentGroup Group { get; set; }

    public virtual ICollection<InvoicesDetails> InvoicesDetails { get; set; } = new List<InvoicesDetails>();
}