// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceUbl
{
    public int Id { get; set; }

    public int InvoiceId { get; set; }

    public string UblVersion { get; set; }

    public string Profile { get; set; }

    public string XmlContent { get; set; }

    public DateTime GeneratedAt { get; set; }

    public bool SentViaPeppol { get; set; }

    public string PeppolDocId { get; set; }

    public virtual Invoices Invoice { get; set; }
}