// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class InvoiceRelations
{
    public int Id { get; set; }

    public int ParentInvoiceId { get; set; }

    public int ChildInvoiceId { get; set; }

    public string RelationType { get; set; }

    public virtual Invoices ChildInvoice { get; set; }

    public virtual Invoices ParentInvoice { get; set; }
}