// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IssuerCompany
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string LegalName { get; set; }

    public string VatNumber { get; set; }

    public string EnterpriseNumber { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string PostalCode { get; set; }

    public string City { get; set; }

    public string CountryCode { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string LogoPath { get; set; }

    public int? DefaultPaymentTermId { get; set; }

    public string PeppolParticipantId { get; set; }

    public bool IsActive { get; set; }

    public int? LegacyCompanyInfoId { get; set; }

    public bool EinvoiceEnabled { get; set; }

    public bool UblAttachPdf { get; set; }

    public string EmailSubjectTemplate { get; set; }

    public string EmailBodyTemplate { get; set; }

    public string InvoiceFooterHtml { get; set; }

    public string DefaultLanguage { get; set; }

    public string DefaultCurrency { get; set; }

    public string InvoiceNumberPattern { get; set; }

    public bool EpcQrEnabled { get; set; }

    public string EpcBeneficiaryName { get; set; }

    public string EpcIban { get; set; }

    public string EpcBic { get; set; }

    public string EpcRemittanceType { get; set; }

    public string EpcRemittanceTemplate { get; set; }

    public int? DefaultVatTypeId { get; set; }

    public string TemplateKey { get; set; }

    public string TemplateJson { get; set; }

    public string BrandPrimaryColor { get; set; }

    public string BrandSecondaryColor { get; set; }

    public string FontFamily { get; set; }

    public byte[] LogoBytes { get; set; }

    public string FooterLegalText { get; set; }

    public bool PeppolEnabled { get; set; }

    public string Phone2 { get; set; }

    public string Website { get; set; }

    public virtual PaymentTerms DefaultPaymentTerm { get; set; }

    public virtual Vattype DefaultVatType { get; set; }

    public virtual ICollection<InvoiceSeries> InvoiceSeries { get; set; } = new List<InvoiceSeries>();

    public virtual ICollection<Invoices> Invoices { get; set; } = new List<Invoices>();

    public virtual IssuerBankAccount IssuerBankAccount { get; set; }
}