// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IssueNotificationRun
{
    public int Id { get; set; }

    public int? ScheduleId { get; set; }

    public int RunType { get; set; }

    public string TriggeredBy { get; set; }

    public DateTime StartedDate { get; set; }

    public DateTime? FinishedDate { get; set; }

    public int Status { get; set; }

    public string ErrorMessage { get; set; }

    public int EmailsSent { get; set; }

    public virtual IssueNotificationSchedule Schedule { get; set; }
}