// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IssueNotificationSchedule
{
    public int Id { get; set; }

    public int? SupplierId { get; set; }

    public int? ProjectId { get; set; }

    public int ReminderFrequencyDays { get; set; }

    public bool SendEveningUpdate { get; set; }

    public int EveningUpdateHour { get; set; }

    public int ReminderHour { get; set; }

    public bool IsActive { get; set; }

    public DateTime? NextReminderRun { get; set; }

    public DateOnly? LastEveningRun { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ReminderDayOfWeek { get; set; }

    public virtual ICollection<IssueNotificationRun> IssueNotificationRun { get; set; } = new List<IssueNotificationRun>();
}