// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class IssuerBankAccount
{
    public int Id { get; set; }

    public int IssuerCompanyId { get; set; }

    public string Iban { get; set; }

    public string Bic { get; set; }

    public string DisplayName { get; set; }

    public bool IsDefault { get; set; }

    public DateOnly? ValidFrom { get; set; }

    public DateOnly? ValidTo { get; set; }

    public virtual IssuerCompany IssuerCompany { get; set; }

    public virtual ICollection<ProjectSalesSettings> ProjectSalesSettings { get; set; } = new List<ProjectSalesSettings>();
}