// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class MarktanalyseZoekProfiel
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Naam { get; set; }

    public string ZoekgebiedTab { get; set; }

    public string GemeenteIdsJson { get; set; }

    public string RondAdresPostcode { get; set; }

    public double? RondAdresLat { get; set; }

    public double? RondAdresLng { get; set; }

    public int RondAdresStraal { get; set; }

    public string Type { get; set; }

    public decimal? Oppervlakte { get; set; }

    public int Tolerantie { get; set; }

    public decimal? PrijsMin { get; set; }

    public decimal? PrijsMax { get; set; }

    public int? Slaapkamers { get; set; }

    public string Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Users User { get; set; }
}
