// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class OctopusJournals
{
    public int Id { get; set; }

    public int BookyearId { get; set; }

    public int BookyearKeyId { get; set; }

    public string JournalKey { get; set; }

    public string Name { get; set; }

    public bool Closed { get; set; }

    public string CurrencyCode { get; set; }

    public int? LastBookedDocumentNr { get; set; }

    public int? ProtectedPeriod { get; set; }

    public int? ClosedPeriod { get; set; }

    public int? InsertionType { get; set; }

    public string CustomFieldListJson { get; set; }

    public string CustomFieldLineListJson { get; set; }

    public virtual OctopusBookyears Bookyear { get; set; }

    public virtual ICollection<InvoiceSequence> InvoiceSequence { get; set; } = new List<InvoiceSequence>();
}