// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class OctopusBookyearPeriods
{
    public int Id { get; set; }

    public int BookyearId { get; set; }

    public int BookyearPeriodNr { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual OctopusBookyears Bookyear { get; set; }
}