// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class OctopusBookyears
{
    public int Id { get; set; }

    public int IssuerCompanyId { get; set; }

    public int BookyearKeyId { get; set; }

    public string BookyearDescription { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool Closed { get; set; }

    public virtual ICollection<InvoiceSequence> InvoiceSequence { get; set; } = new List<InvoiceSequence>();

    public virtual IssuerCompany IssuerCompany { get; set; }

    public virtual ICollection<OctopusBookyearPeriods> OctopusBookyearPeriods { get; set; } = new List<OctopusBookyearPeriods>();

    public virtual ICollection<OctopusJournals> OctopusJournals { get; set; } = new List<OctopusJournals>();
}