// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class PaymentTerms
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Days { get; set; }

    public string Description { get; set; }

    public int TermType { get; set; }

    public int DisplayMode { get; set; }

    public string DisplayText { get; set; }

    public int? IssuerCompanyId { get; set; }

    public virtual ICollection<IssuerCompany> IssuerCompany { get; set; } = new List<IssuerCompany>();

    public virtual IssuerCompany IssuerCompanyNavigation { get; set; }
}