// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Payments
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public DateOnly ReceivedDate { get; set; }

    public decimal Amount { get; set; }

    public string CurrencyCode { get; set; }

    public decimal? FxRateToCompany { get; set; }

    public string Method { get; set; }

    public string BankTxnId { get; set; }

    public string PspReference { get; set; }

    public string PayerName { get; set; }

    public string StructuredComm { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<PaymentAllocations> PaymentAllocations { get; set; } = new List<PaymentAllocations>();
}