// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class PermissionPerUser
{
    public int PermissionId { get; set; }

    public int UserId { get; set; }

    public int? Permission { get; set; }

    public virtual Permission PermissionNavigation { get; set; }

    public virtual Users User { get; set; }
}