// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class PlanningSectie
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int? ActivityGroupId { get; set; }

    public string Naam { get; set; }

    public int Volgorde { get; set; }

    public bool IsActief { get; set; }

    public virtual ActivityGroup ActivityGroup { get; set; }

    public virtual ICollection<PlanningTaak> PlanningTaak { get; set; } = new List<PlanningTaak>();

    public virtual Project Project { get; set; }
}