// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class PlanningTaak
{
    public int Id { get; set; }

    public int PlanningSectieId { get; set; }

    public string Naam { get; set; }

    public string Beschrijving { get; set; }

    public DateOnly? Startdatum { get; set; }

    public DateOnly? Einddatum { get; set; }

    public DateOnly? AfgerondOp { get; set; }

    public bool IsAfgerond { get; set; }

    public int VoortgangPct { get; set; }

    public int Volgorde { get; set; }

    public virtual PlanningSectie PlanningSectie { get; set; }
}