// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class PostalCode
{
    public int PostcodeId { get; set; }

    public string Postcode { get; set; }

    public string Gemeente { get; set; }

    public int? CountryId { get; set; }

    public int? ProvincieId { get; set; }

    public virtual ICollection<ClientAccount> ClientAccountInvoicePostalCode { get; set; } = new List<ClientAccount>();

    public virtual ICollection<ClientAccount> ClientAccountPostalCode { get; set; } = new List<ClientAccount>();

    public virtual ICollection<ClientContacts> ClientContactsInvoicePostalCode { get; set; } = new List<ClientContacts>();

    public virtual ICollection<ClientContacts> ClientContactsPostalCode { get; set; } = new List<ClientContacts>();

    public virtual ICollection<CompanyDepartments> CompanyDepartments { get; set; } = new List<CompanyDepartments>();

    public virtual ICollection<CompanyInfo> CompanyInfo { get; set; } = new List<CompanyInfo>();

    public virtual Country Country { get; set; }

    public virtual ICollection<InsuranceCompanies> InsuranceCompanies { get; set; } = new List<InsuranceCompanies>();

    public virtual ICollection<Invoices> Invoices { get; set; } = new List<Invoices>();

    public virtual ICollection<Project> Project { get; set; } = new List<Project>();

    public virtual Provincie Provincie { get; set; }
}