// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectRegieUur
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string UserId { get; set; }

    public DateOnly Date { get; set; }

    public decimal Hours { get; set; }

    public bool WithTravel { get; set; }

    public decimal? TravelKm { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? InvoiceId { get; set; }

    public virtual Project Project { get; set; }

    public virtual Users User { get; set; }

    public virtual Invoices Invoice { get; set; }
}
