// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectLevels
{
    public int Id { get; set; }

    public string Level { get; set; }

    public int ProjectId { get; set; }

    public int? Number { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<Units> Units { get; set; } = new List<Units>();
}