// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectNews
{
    public int Id { get; set; }

    public string TitleNl { get; set; }

    public string TextNl { get; set; }

    public DateTime Date { get; set; }

    public int? PictureId { get; set; }

    public int ProjectId { get; set; }

    public string Author { get; set; }

    public virtual ProjectPictures Picture { get; set; }

    public virtual Project Project { get; set; }
}