// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectMediaSection
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int SortOrder { get; set; }

    public bool IsPublic { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<ProjectPictures> ProjectPictures { get; set; } = new List<ProjectPictures>();
}