// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectContractSlice
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string Description { get; set; }

    public decimal Percentage { get; set; }

    public int SortOrder { get; set; }

    public int? InvoiceId { get; set; }

    public virtual Invoices Invoice { get; set; }

    public virtual Project Project { get; set; }
}