// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectPictures
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? Datetimeuploaded { get; set; }

    public int? ProjectId { get; set; }

    public string Caption { get; set; }

    public int? Type { get; set; }

    public string FacebookIdCopro { get; set; }

    public int? SectionId { get; set; }

    public bool IsPublic { get; set; }

    public int SortOrder { get; set; }

    public int MediaType { get; set; }

    public long? FileSizeBytes { get; set; }

    public int? WidthPx { get; set; }

    public int? HeightPx { get; set; }

    public double? DurationSeconds { get; set; }

    public virtual ICollection<Project> Project { get; set; } = new List<Project>();

    public virtual Project ProjectNavigation { get; set; }

    public virtual ICollection<ProjectNews> ProjectNews { get; set; } = new List<ProjectNews>();

    public virtual ProjectMediaSection Section { get; set; }
}