// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectVoortgang
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public decimal FysiekeVoortgangPct { get; set; }

    public decimal FinancieleVoortgangPct { get; set; }

    public decimal ContractueleVolwassenheidPct { get; set; }

    public int Fase { get; set; }

    public string Warnings { get; set; }

    public decimal? TotaalBegroot { get; set; }

    public decimal? TotaalGecontracteerd { get; set; }

    public decimal? TotaalGefactureerd { get; set; }

    public DateTime BerekendOp { get; set; }

    public bool ManueelAfgesloten { get; set; }

    public virtual Project Project { get; set; }
}