// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BOCore;   

namespace DALCore.Models;

public partial class ProjectDocs
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int? ClientAccountId { get; set; }

    public string Name { get; set; }

    public string Filename { get; set; }

    public int SortOrder { get; set; }

    public int? Type { get; set; }

    public DateOnly? Date { get; set; }

    public virtual ClientAccount ClientAccount { get; set; }

    public virtual ICollection<InvoicingPaymentStages> InvoicingPaymentStages { get; set; } = new List<InvoicingPaymentStages>();

    public virtual Project Project { get; set; }
    public IdNameBO GetIdName()
    {
        IdNameBO bo = new IdNameBO();
        bo.ID = this.Id;
        bo.Display = this.Name;
        return bo;
    }

}