// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectHourlyRate
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string UserId { get; set; }

    public decimal HourlyRate { get; set; }

    public virtual Project Project { get; set; }

    public virtual Users User { get; set; }
}