// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Project
{
    public int ProjectId { get; set; }

    public string ProjectName { get; set; }

    public string Slug { get; set; }

    public int? PostalCodeId { get; set; }

    public string Street { get; set; }

    public string Number { get; set; }

    public int? StatusId { get; set; }

    public string CommercialTitleNl { get; set; }

    public string CommercialTextNl { get; set; }

    public DateOnly? ConstructionYear { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public DateOnly? DeliveryDateDef { get; set; }

    public DateOnly? StartDateConstruction { get; set; }

    public int? DeveloperId { get; set; }

    public int? BuilderId { get; set; }

    public int? ExecutionDays { get; set; }

    public int? WheaterStationId { get; set; }

    public int? DefaultPictureId { get; set; }

    public int? EngineerId { get; set; }

    public int? SecurityCoordinatorId { get; set; }

    public int? EpbReporterId { get; set; }

    public int? ArchitectId { get; set; }

    public decimal? FacebookAlbumId { get; set; }

    public string AspNetUserId { get; set; }

    public decimal? TotalLandShare { get; set; }

    public string FacebookPlaceId { get; set; }

    public string ProjectFolder { get; set; }

    public bool? UploadToFacebook { get; set; }

    public bool? DocPid { get; set; }

    public bool? DocElectricalInspection { get; set; }

    public bool? DocWaterInspection { get; set; }

    public bool? DocSewerInspection { get; set; }

    public bool? DocFireInspection { get; set; }

    public bool? DocDelivery { get; set; }

    public bool? DocDefDelivery { get; set; }

    public int ProjectType { get; set; }

    public int? IssuerCompanyIdBuilder { get; set; }

    public int? IssuerCompanyIdLandOwner { get; set; }

    public bool IsCoordinationProject { get; set; }

    public int? CoordinationIssuerCompanyId { get; set; }

    public int? ContractType { get; set; }

    public decimal? ProjectDistanceKm { get; set; }

    public decimal? KmAllowance { get; set; }

    public int? RouteDurationSeconds { get; set; }

    public string CoordinationReference { get; set; }

    public bool IsPublished { get; set; }

    public bool IsOnlyCoordinationProject { get; set; }

    public string StandardFotoName { get; set; }

    public string SeoTitle { get; set; }

    public string SeoDescription { get; set; }

    public DateOnly? WerfmeldingDate { get; set; }

    public string WerfmeldingDossier { get; set; }

    public virtual CompanyInfo Architect { get; set; }

    public virtual Users AspNetUser { get; set; }

    public virtual CompanyInfo Builder { get; set; }

    public virtual ICollection<ConnectionSettlement> ConnectionSettlement { get; set; } = new List<ConnectionSettlement>();

    public virtual ICollection<ConstructionIssue> ConstructionIssue { get; set; } = new List<ConstructionIssue>();

    public virtual ICollection<ConstructionIssueReport> ConstructionIssueReport { get; set; } = new List<ConstructionIssueReport>();

    public virtual ICollection<ContactRequests> ContactRequests { get; set; } = new List<ContactRequests>();

    public virtual ICollection<Contract> Contract { get; set; } = new List<Contract>();

    public virtual IssuerCompany CoordinationIssuerCompany { get; set; }

    public virtual ProjectPictures DefaultPicture { get; set; }

    public virtual CompanyInfo Developer { get; set; }

    public virtual CompanyInfo Engineer { get; set; }

    public virtual CompanyInfo EpbReporter { get; set; }

    public virtual ICollection<IncomingInvoiceEnrichment> IncomingInvoiceEnrichmentSuggestedProject { get; set; } = new List<IncomingInvoiceEnrichment>();

    public virtual ICollection<IncomingInvoiceEnrichment> IncomingInvoiceEnrichmentUserConfirmedProject { get; set; } = new List<IncomingInvoiceEnrichment>();

    public virtual ICollection<IncommingInvoices> IncommingInvoices { get; set; } = new List<IncommingInvoices>();

    public virtual ICollection<InvoiceProjectAlias> InvoiceProjectAlias { get; set; } = new List<InvoiceProjectAlias>();

    public virtual ICollection<InvoiceSupplierRule> InvoiceSupplierRule { get; set; } = new List<InvoiceSupplierRule>();

    public virtual ICollection<InvoicingPaymentGroup> InvoicingPaymentGroup { get; set; } = new List<InvoicingPaymentGroup>();

    public virtual IssuerCompany IssuerCompanyIdBuilderNavigation { get; set; }

    public virtual IssuerCompany IssuerCompanyIdLandOwnerNavigation { get; set; }

    public virtual ICollection<PlanningSectie> PlanningSectie { get; set; } = new List<PlanningSectie>();

    public virtual PostalCode PostalCode { get; set; }

    public virtual ICollection<ProjectBudget> ProjectBudget { get; set; } = new List<ProjectBudget>();

    public virtual ICollection<ProjectConnectionKey> ProjectConnectionKey { get; set; } = new List<ProjectConnectionKey>();

    public virtual ICollection<ProjectContractSlice> ProjectContractSlice { get; set; } = new List<ProjectContractSlice>();

    public virtual ICollection<ProjectDocs> ProjectDocs { get; set; } = new List<ProjectDocs>();

    public virtual ICollection<ProjectHourlyRate> ProjectHourlyRate { get; set; } = new List<ProjectHourlyRate>();

    public virtual ICollection<ProjectLevels> ProjectLevels { get; set; } = new List<ProjectLevels>();

    public virtual ICollection<ProjectMediaSection> ProjectMediaSection { get; set; } = new List<ProjectMediaSection>();

    public virtual ICollection<ProjectNews> ProjectNews { get; set; } = new List<ProjectNews>();

    public virtual ICollection<ProjectPictures> ProjectPictures { get; set; } = new List<ProjectPictures>();

    public virtual ICollection<ProjectRegieUur> ProjectRegieUur { get; set; } = new List<ProjectRegieUur>();

    public virtual ICollection<ProjectSalesSettings> ProjectSalesSettings { get; set; } = new List<ProjectSalesSettings>();

    public virtual ICollection<ProjectUserAccess> ProjectUserAccess { get; set; } = new List<ProjectUserAccess>();

    public virtual ProjectVoortgang ProjectVoortgang { get; set; }

    public virtual CompanyInfo SecurityCoordinator { get; set; }

    public virtual ProjectStatus Status { get; set; }

    public virtual ICollection<Units> Units { get; set; } = new List<Units>();

    public virtual ICollection<UserPinnedProject> UserPinnedProject { get; set; } = new List<UserPinnedProject>();

    public virtual ICollection<UserProjectSortOrder> UserProjectSortOrder { get; set; } = new List<UserProjectSortOrder>();

    public virtual ICollection<VacationDays> VacationDays { get; set; } = new List<VacationDays>();

    public virtual WheaterStations WheaterStation { get; set; }

    public virtual ICollection<CompanyInfo> Company { get; set; } = new List<CompanyInfo>();
}