// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectConnectionKey
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int UnitId { get; set; }

    public decimal Weight { get; set; }

    public virtual Project Project { get; set; }

    public virtual Units Unit { get; set; }
}