// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class ProjectBudget
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int ActivityId { get; set; }

    public decimal Price { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual Project Project { get; set; }
}