// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Provincie
{
    public int ProvincieId { get; set; }

    public string ProvincieName { get; set; }

    public int CountryId { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<PostalCode> PostalCode { get; set; } = new List<PostalCode>();
}