// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class SecurityRolePermission
{
    public int RoleId { get; set; }

    public string PermissionCode { get; set; }

    public bool CanRead { get; set; }

    public bool CanWrite { get; set; }

    public bool CanDelete { get; set; }

    public virtual SecurityPermission PermissionCodeNavigation { get; set; }

    public virtual SecurityRole Role { get; set; }
}