// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class SecurityRole
{
    public int RoleId { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<SecurityRolePermission> SecurityRolePermission { get; set; } = new List<SecurityRolePermission>();

    public virtual ICollection<SecurityUserRole> SecurityUserRole { get; set; } = new List<SecurityUserRole>();
}