// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class SecurityUserRole
{
    public int UserId { get; set; }

    public int RoleId { get; set; }

    public int Id { get; set; }

    public virtual SecurityRole Role { get; set; }

    public virtual Users User { get; set; }
}