// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class SecurityPermission
{
    public string Code { get; set; }

    public string Name { get; set; }

    public string ParentCode { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<SecurityRolePermission> SecurityRolePermission { get; set; } = new List<SecurityRolePermission>();

    public virtual ICollection<SecurityUserPermissionOverride> SecurityUserPermissionOverride { get; set; } = new List<SecurityUserPermissionOverride>();
}