// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Setting
{
    public decimal SettingId { get; set; }

    public string SettingName { get; set; }

    public decimal? ValueNum { get; set; }

    public string ValueString { get; set; }

    public bool? ValueBoolean { get; set; }
}