// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UnitTypes
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int GroupId { get; set; }

    public string Shortcode { get; set; }

    public bool? Selectable { get; set; }

    public virtual UnitGroupTypes Group { get; set; }

    public virtual ICollection<Units> Units { get; set; } = new List<Units>();
}