// <auto-generated> Handmatig toegevoegd, zelfde stijl als de EF Core Power Tools-gegenereerde modellen
// hiernaast (migratie 062_UnitPaymentStageReached.sql). </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

/// <summary>Schijf bereikt aanduiden per eenheid (design-handoff 21g/21h) — een aanvulling op, geen
/// vervanging van, InvoicingPaymentStages.Invoicable (die blijft de groep-brede vlag). Zie de migratie
/// voor de volledige toelichting.</summary>
public partial class UnitPaymentStageReached
{
    public int Id { get; set; }

    public int UnitId { get; set; }

    public int PaymentStageId { get; set; }

    public DateOnly ReachedDate { get; set; }

    public int? ReachedByUserId { get; set; }

    public int? ProofDocId { get; set; }

    /// <summary>Werffoto uit de project-Media (ProjectPictures), niet uit Documenten — zie migratie
    /// 063. ProofDocId hierboven blijft ongebruikt staan (additief-only).</summary>
    public int? ProofMediaId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Units Unit { get; set; }

    public virtual InvoicingPaymentStages PaymentStage { get; set; }

    public virtual ProjectDocs ProofDoc { get; set; }

    public virtual ProjectPictures ProofMedia { get; set; }
}
