// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UnitExecutionPlan
{
    public int Id { get; set; }

    public int UnitId { get; set; }

    public string Name { get; set; }

    public string FileId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedByUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedByUserId { get; set; }

    public virtual Units Unit { get; set; }
}