// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UnitConstructionValue
{
    public int Id { get; set; }

    public decimal? Value { get; set; }

    public decimal? ValueSold { get; set; }

    public string Description { get; set; }

    public int? PaymentGroupId { get; set; }

    public int UnitId { get; set; }

    public virtual InvoicingPaymentGroup PaymentGroup { get; set; }

    public virtual Units Unit { get; set; }
}