// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UnitGroupTypes
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool Selectable { get; set; }

    public virtual ICollection<UnitTypes> UnitTypes { get; set; } = new List<UnitTypes>();
}