// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UnitFinishingOption
{
    public int Id { get; set; }

    public int UnitId { get; set; }

    public string Name { get; set; }

    public int SortOrder { get; set; }

    public bool IsDefault { get; set; }

    public virtual Units Unit { get; set; }

    public virtual ICollection<UnitConstructionValue> UnitConstructionValue { get; set; } = new List<UnitConstructionValue>();
}