// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UnitRooms
{
    public int RoomId { get; set; }

    public int UnitId { get; set; }

    public int Type { get; set; }

    public int Number { get; set; }

    public decimal? Surface { get; set; }

    public string Remark { get; set; }

    public virtual Units Unit { get; set; }
}