// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UserCoachmarkState
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string FeatureKey { get; set; }

    public DateTime? FirstShownAt { get; set; }

    public DateTime? LastShownAt { get; set; }

    public bool Dismissed { get; set; }

    public DateTime? DismissedAt { get; set; }

    public bool Completed { get; set; }

    public DateTime? CompletedAt { get; set; }

    public int CurrentStep { get; set; }

    public int ShowCount { get; set; }

    public virtual Users User { get; set; }
}