// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Users
{
    public string UserId { get; set; }

    public string Password { get; set; }

    public decimal? Type { get; set; }

    public string Voornaam { get; set; }

    public string Familienaam { get; set; }

    public string Functie { get; set; }

    public string Gsm { get; set; }

    public string Initiaal { get; set; }

    public string Email { get; set; }

    public int Id { get; set; }

    public string EntraObjectId { get; set; }

    public bool IsActive { get; set; }

    public byte[] Photo { get; set; }

    public string PhotoContentType { get; set; }

    public string PhotoHash { get; set; }

    public int? DashboardType { get; set; }

    public virtual ICollection<IssuerCompanyUserRate> IssuerCompanyUserRate { get; set; } = new List<IssuerCompanyUserRate>();

    public virtual ICollection<PermissionPerUser> PermissionPerUser { get; set; } = new List<PermissionPerUser>();

    public virtual ICollection<Project> Project { get; set; } = new List<Project>();

    public virtual ICollection<ProjectHourlyRate> ProjectHourlyRate { get; set; } = new List<ProjectHourlyRate>();

    public virtual ICollection<ProjectRegieUur> ProjectRegieUur { get; set; } = new List<ProjectRegieUur>();

    public virtual ICollection<ProjectUserAccess> ProjectUserAccess { get; set; } = new List<ProjectUserAccess>();

    public virtual ICollection<SecurityUserPermissionOverride> SecurityUserPermissionOverride { get; set; } = new List<SecurityUserPermissionOverride>();

    public virtual ICollection<SecurityUserRole> SecurityUserRole { get; set; } = new List<SecurityUserRole>();

    public virtual ICollection<UserCoachmarkState> UserCoachmarkState { get; set; } = new List<UserCoachmarkState>();

    public virtual ICollection<UserCompanyAccess> UserCompanyAccess { get; set; } = new List<UserCompanyAccess>();

    public virtual ICollection<UserGuestInvitation> UserGuestInvitationInvitedByUser { get; set; } = new List<UserGuestInvitation>();

    public virtual ICollection<UserGuestInvitation> UserGuestInvitationUser { get; set; } = new List<UserGuestInvitation>();
}