// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UserCompanyAccess
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CompanyId { get; set; }

    public int Role { get; set; }

    public virtual CompanyInfo Company { get; set; }

    public virtual Users User { get; set; }
}