// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UserGuestInvitation
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Provider { get; set; }

    public string ExternalObjectId { get; set; }

    public string ExternalTenantId { get; set; }

    public string ExternalEmail { get; set; }

    public string UserType { get; set; }

    public string InvitationStatus { get; set; }

    public DateTime? InvitationSentAt { get; set; }

    public DateTime? InvitationRedeemedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public string InviteRedeemUrl { get; set; }

    public int? InvitedByUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Users InvitedByUser { get; set; }

    public virtual Users User { get; set; }
}