// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UserGuestInvitationAudit
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Action { get; set; }

    public string Details { get; set; }

    public int? PerformedBy { get; set; }

    public DateTime PerformedAt { get; set; }
}