// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UserPinnedProject
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int ProjectId { get; set; }

    public DateTime PinnedAt { get; set; }

    public virtual Project Project { get; set; }

    public virtual Users User { get; set; }
}
