// Hand-written model — not auto-generated by EF Core Power Tools
#nullable disable
using System;

namespace DALCore.Models;

public partial class UserCoachmarkState
{
    public int Id { get; set; }

    /// <summary>
    /// FK naar Users.Id
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Voor single coachmarks: de FeatureKey van de definitie.
    /// Voor sequences: de SequenceKey.
    /// </summary>
    public string FeatureKey { get; set; }

    public DateTime? FirstShownAt { get; set; }

    public DateTime? LastShownAt { get; set; }

    public bool Dismissed { get; set; }

    public DateTime? DismissedAt { get; set; }

    public bool Completed { get; set; }

    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Huidige stap (enkel relevant voor sequences).
    /// </summary>
    public int CurrentStep { get; set; }

    /// <summary>
    /// Totaal aantal keren getoond.
    /// </summary>
    public int ShowCount { get; set; }

    public virtual Users User { get; set; }
}
