// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Users
{
    public string UserId { get; set; }

    public string Password { get; set; }

    public decimal? Type { get; set; }

    public string Voornaam { get; set; }

    public string Familienaam { get; set; }

    public string Functie { get; set; }

    public string Gsm { get; set; }

    public string Initiaal { get; set; }

    public string Email { get; set; }

    public int Id { get; set; }

    public virtual ICollection<PermissionPerUser> PermissionPerUser { get; set; } = new List<PermissionPerUser>();
}