// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UserCompany
{
    public decimal? UserCompanyId { get; set; }

    public string UserCompanyName { get; set; }
}