// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class UtilityPercentage
{
    public int ClientAccountId { get; set; }

    public int? IncommingInvoiceDetailId { get; set; }

    public int? ContractId { get; set; }

    public decimal Percentage { get; set; }

    public virtual ClientAccount ClientAccount { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual IncommingInvoiceDetail IncommingInvoiceDetail { get; set; }
}