// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class VacationDays
{
    public int Id { get; set; }

    public DateOnly VacationDay { get; set; }

    public int? ProjectId { get; set; }

    public virtual Project Project { get; set; }
}