// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Vattype
{
    public int Id { get; set; }

    public int IssuerCompanyId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public int Type { get; set; }

    public decimal BasePercentage { get; set; }

    public int? DefaultSellBookingAccountNr { get; set; }

    public string InvoiceMention { get; set; }

    public virtual ICollection<IssuerCompany> IssuerCompany { get; set; } = new List<IssuerCompany>();

    public virtual IssuerCompany IssuerCompanyNavigation { get; set; }
}