// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class Vattype
{
    public int Id { get; set; }

    public int Vatpercentage { get; set; }

    public string Vattext { get; set; }
}