// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class VwInvoiceTotals
{
    public int Id { get; set; }

    public decimal? LinesNet { get; set; }

    public decimal? LinesVat { get; set; }

    public decimal Rounding { get; set; }

    public decimal? GrossTotal { get; set; }
}