// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class VwInvoiceBalance
{
    public int Id { get; set; }

    public decimal? GrossTotal { get; set; }

    public decimal Paid { get; set; }

    public decimal? Balance { get; set; }
}