// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DALCore.Models;

public partial class WheaterStations
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool? Visible { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual ICollection<BadWeatherDays> BadWeatherDays { get; set; } = new List<BadWeatherDays>();

    public virtual ICollection<Project> Project { get; set; } = new List<Project>();
}