Public NotInheritable Class PermissionCatalog

    Public Shared ReadOnly Property All As IReadOnlyList(Of PermissionDefinition) =
        New List(Of PermissionDefinition) From {
            New PermissionDefinition(PermissionCodes.Dashboard, "Dashboard", Nothing, 10),
            New PermissionDefinition(PermissionCodes.Suppliers, "Leveranciers", Nothing, 20),
            New PermissionDefinition(PermissionCodes.SuppliersAll, "Alle leveranciers", PermissionCodes.Suppliers, 21),
            New PermissionDefinition(PermissionCodes.SuppliersByBillingCompany, "Per facturatiebedrijf", PermissionCodes.Suppliers, 22),
            New PermissionDefinition(PermissionCodes.Customers, "Klanten", Nothing, 30),
            New PermissionDefinition(PermissionCodes.CustomersAll, "Alle klanten", PermissionCodes.Customers, 31),
            New PermissionDefinition(PermissionCodes.CustomersByBillingCompany, "Per facturatiebedrijf", PermissionCodes.Customers, 32),
            New PermissionDefinition(PermissionCodes.Projects, "Projecten", Nothing, 40),
            New PermissionDefinition(PermissionCodes.ProjectsWeatherDelay, "Weerverlet", PermissionCodes.Projects, 41),
            New PermissionDefinition(PermissionCodes.ProjectsAlgemeen, "Algemeen", PermissionCodes.Projects, 42),
            New PermissionDefinition(PermissionCodes.ProjectsDetail, "Project", PermissionCodes.ProjectsAlgemeen, 43),
            New PermissionDefinition(PermissionCodes.ProjectsCustomers, "Klanten", PermissionCodes.ProjectsAlgemeen, 44),
            New PermissionDefinition(PermissionCodes.ProjectsSuppliers, "Leveranciers", PermissionCodes.ProjectsAlgemeen, 45),
            New PermissionDefinition(PermissionCodes.ProjectsDetails, "Details", PermissionCodes.Projects, 46),
            New PermissionDefinition(PermissionCodes.ProjectsPhotos, "Media", PermissionCodes.ProjectsDetails, 47),
            New PermissionDefinition(PermissionCodes.ProjectsNews, "Nieuws", PermissionCodes.ProjectsDetails, 48),
            New PermissionDefinition(PermissionCodes.ProjectsUnits, "Eenheden", PermissionCodes.ProjectsDetails, 49),
            New PermissionDefinition(PermissionCodes.ProjectsOpvolging, "Opvolging", PermissionCodes.Projects, 50),
            New PermissionDefinition(PermissionCodes.ProjectsIssues, "Punten", PermissionCodes.ProjectsOpvolging, 51),
            New PermissionDefinition(PermissionCodes.ProjectsDocuments, "Documenten", PermissionCodes.ProjectsOpvolging, 52),
            New PermissionDefinition(PermissionCodes.ProjectsInsurances, "Verzekeringen", PermissionCodes.ProjectsOpvolging, 53),
            New PermissionDefinition(PermissionCodes.ProjectsDetailCoordinatie, "Coördinatie", PermissionCodes.ProjectsOpvolging, 54),
            New PermissionDefinition(PermissionCodes.ProjectsFinancieel, "Financieel", PermissionCodes.Projects, 55),
            New PermissionDefinition(PermissionCodes.ProjectsBudgetIndex, "Budget", PermissionCodes.ProjectsFinancieel, 56),
            New PermissionDefinition(PermissionCodes.ProjectsInvoicing, "Facturatie", PermissionCodes.ProjectsFinancieel, 57),
            New PermissionDefinition(PermissionCodes.ProjectsPostCalculation, "Nacalculatie", PermissionCodes.ProjectsFinancieel, 58),
            New PermissionDefinition(PermissionCodes.ProjectsChangeOrders, "Wijzigingsopdrachten", PermissionCodes.ProjectsFinancieel, 59),
            New PermissionDefinition(PermissionCodes.ProjectsVerkoop, "Verkoop", PermissionCodes.Projects, 60),
            New PermissionDefinition(PermissionCodes.ProjectsForSale, "Te Koop", PermissionCodes.ProjectsVerkoop, 61),
            New PermissionDefinition(PermissionCodes.ProjectsContacts, "Contacten", PermissionCodes.ProjectsVerkoop, 62),
            New PermissionDefinition(PermissionCodes.Invoicing, "Facturatie", Nothing, 70),
            New PermissionDefinition(PermissionCodes.InvoicingByBillingCompany, "Per facturatiebedrijf", PermissionCodes.Invoicing, 71),
            New PermissionDefinition(PermissionCodes.Settings, "Instellingen", Nothing, 80),
            New PermissionDefinition(PermissionCodes.SettingsFacturatieEnBoekhouding, "Facturatie en boekhouding", PermissionCodes.Settings, 81),
            New PermissionDefinition(PermissionCodes.SettingsBillingCompanies, "Mijn bedrijven", PermissionCodes.SettingsFacturatieEnBoekhouding, 82),
            New PermissionDefinition(PermissionCodes.SettingsInvoiceTemplates, "Factuurtemplates", PermissionCodes.SettingsFacturatieEnBoekhouding, 83),
            New PermissionDefinition(PermissionCodes.SettingsBouwIndexen, "Bouwindexen", PermissionCodes.SettingsFacturatieEnBoekhouding, 84),
            New PermissionDefinition(PermissionCodes.SettingsTeamEnToegang, "Team en toegang", PermissionCodes.Settings, 85),
            New PermissionDefinition(PermissionCodes.SettingsUsers, "Gebruikers", PermissionCodes.SettingsTeamEnToegang, 86),
            New PermissionDefinition(PermissionCodes.SettingsRoles, "Rollen", PermissionCodes.SettingsTeamEnToegang, 87),
            New PermissionDefinition(PermissionCodes.SettingsHolidays, "Verlofdagen", PermissionCodes.SettingsTeamEnToegang, 88),
            New PermissionDefinition(PermissionCodes.SettingsCalculatie, "Calculatie", PermissionCodes.Settings, 89),
            New PermissionDefinition(PermissionCodes.SettingsActivities, "Activiteiten", PermissionCodes.SettingsCalculatie, 90),
            New PermissionDefinition(PermissionCodes.SettingsKostprijsMaterialen, "Kostprijs materialen", PermissionCodes.SettingsCalculatie, 91),
            New PermissionDefinition(PermissionCodes.SettingsWebsite, "Website", PermissionCodes.Settings, 92),
            New PermissionDefinition(PermissionCodes.SettingsBlogBeheer, "Blog artikelen", PermissionCodes.SettingsWebsite, 93),
            New PermissionDefinition(PermissionCodes.SettingsAutomatisatie, "Automatisatie", PermissionCodes.Settings, 94),
            New PermissionDefinition(PermissionCodes.SettingsIssueNotifications, "Puntmeldingen", PermissionCodes.SettingsAutomatisatie, 95),
            New PermissionDefinition(PermissionCodes.Marktanalyse, "Marktanalyse", Nothing, 90),
            New PermissionDefinition(PermissionCodes.DocumentCenter, "Documentencentrum", Nothing, 100),
            New PermissionDefinition(PermissionCodes.DocumentCenterByBillingCompany, "Per facturatiebedrijf", PermissionCodes.DocumentCenter, 101)
        }

End Class
