Public NotInheritable Class PermissionCodes

    Public Const Dashboard As String = "Dashboard"
    Public Const Suppliers As String = "Suppliers"
    Public Const SuppliersAll As String = "Suppliers.All"
    Public Const SuppliersByBillingCompany As String = "Suppliers.ByBillingCompany"
    Public Const Customers As String = "Customers"
    Public Const CustomersAll As String = "Customers.All"
    Public Const CustomersByBillingCompany As String = "Customers.ByBillingCompany"
    Public Const Projects As String = "Projects"
    Public Const ProjectsWeatherDelay As String = "Projects.WeatherDelay"
    Public Const ProjectsDetail As String = "Projects.Detail"
    Public Const ProjectsCustomers As String = "Projects.Customers"
    Public Const ProjectsSuppliers As String = "Projects.Suppliers"
    Public Const ProjectsPhotos As String = "Projects.Photos"
    Public Const ProjectsNews As String = "Projects.News"
    Public Const ProjectsUnits As String = "Projects.Units"
    Public Const ProjectsIssues As String = "Projects.Issues"
    Public Const ProjectsDocuments As String = "Projects.Documents"
    Public Const ProjectsInsurances As String = "Projects.Insurances"
    Public Const ProjectsInvoicing As String = "Projects.Invoicing"
    Public Const ProjectsPostCalculation As String = "Projects.PostCalculation"
    Public Const ProjectsChangeOrders As String = "Projects.ChangeOrders"
    Public Const ProjectsForSale As String = "Projects.ForSale"
    Public Const ProjectsContacts As String = "Projects.Contacts"
    Public Const Invoicing As String = "Invoicing"
    Public Const InvoicingByBillingCompany As String = "Invoicing.ByBillingCompany"
    Public Const Settings As String = "Settings"
    Public Const SettingsHolidays As String = "Settings.Holidays"
    Public Const SettingsBillingCompanies As String = "Settings.BillingCompanies"
    Public Const SettingsUsers As String = "Settings.Users"
    Public Const SettingsInvoiceTemplates As String = "Settings.InvoiceTemplates"
    Public Const SettingsActivities As String = "Settings.Activities"
    Public Const SettingsIssueNotifications As String = "Settings.IssueNotifications"

End Class
