'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Activity
    Public Property ActivityID As Integer
    Public Property Omschrijving As String
    Public Property GroupID As Integer

    Public Overridable Property ActivityGroup As ActivityGroup
    Public Overridable Property CompanyInfo As ICollection(Of CompanyInfo) = New HashSet(Of CompanyInfo)
    Public Overridable Property ClientGift As ICollection(Of ClientGift) = New HashSet(Of ClientGift)
    Public Overridable Property ProjectBudget As ICollection(Of ProjectBudget) = New HashSet(Of ProjectBudget)
    Public Overridable Property ContractActivity As ICollection(Of ContractActivity) = New HashSet(Of ContractActivity)
    Public Overridable Property ClientPOA As ICollection(Of ClientPOA) = New HashSet(Of ClientPOA)
    Public Overridable Property IncommingInvoiceDetail As ICollection(Of IncommingInvoiceDetail) = New HashSet(Of IncommingInvoiceDetail)

End Class
