'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetUsers
    Public Property Id As String
    Public Property Cellphone As String
    Public Property Name As String
    Public Property Forename As String
    Public Property JobFunction As String
    Public Property Email As String
    Public Property EmailConfirmed As Boolean
    Public Property PasswordHash As String
    Public Property SecurityStamp As String
    Public Property PhoneNumber As String
    Public Property PhoneNumberConfirmed As Boolean
    Public Property TwoFactorEnabled As Boolean
    Public Property LockoutEndDateUtc As Nullable(Of Date)
    Public Property LockoutEnabled As Boolean
    Public Property AccessFailedCount As Integer
    Public Property UserName As String
    Public Property NormalizedUserName As String
    Public Property NormalizedEmail As String
    Public Property LockoutEnd As Nullable(Of System.DateTimeOffset)
    Public Property ConcurrencyStamp As String

    Public Overridable Property Project As ICollection(Of Project) = New HashSet(Of Project)

End Class
