'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BadWeatherDays
    Public Property Id As Integer
    Public Property [Date] As Date
    Public Property WeatherstationId As Integer
    Public Property Type As Integer

    Public Overridable Property WheaterStations As WheaterStations

End Class
