'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ChangeOrderDetail
    Public Property ID As Integer
    Public Property ChangeOrderID As Integer
    Public Property Description As String
    Public Property MeasurementType As Nullable(Of Integer)
    Public Property MeasurementUnit As Nullable(Of Integer)
    Public Property Number As Integer
    Public Property Price As Decimal
    Public Property Commission As Decimal
    Public Property Invoicable As Nullable(Of Boolean)
    Public Property Invoiced As Nullable(Of Boolean)

    Public Overridable Property ChangeOrder As ChangeOrder
    Public Overridable Property InvoicesDetails As ICollection(Of InvoicesDetails) = New HashSet(Of InvoicesDetails)

End Class
