'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ChangeOrder
    Public Property ID As Integer
    Public Property ClientAccountID As Integer
    Public Property Description As String
    Public Property [Date] As Date
    Public Property ExpirationDate As Date
    Public Property Comment As String
    Public Property DateSendToClient As Nullable(Of Date)
    Public Property DateAgreement As Nullable(Of Date)
    Public Property Invoiceable As Boolean
    Public Property ContractActivityID As Integer
    Public Property ChangeOrderConditions As String

    Public Overridable Property ClientAccount As ClientAccount
    Public Overridable Property ContractActivity As ContractActivity
    Public Overridable Property ChangeOrderDetail As ICollection(Of ChangeOrderDetail) = New HashSet(Of ChangeOrderDetail)
    Public Overridable Property IncommingInvoiceDetail As ICollection(Of IncommingInvoiceDetail) = New HashSet(Of IncommingInvoiceDetail)

End Class
