'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientAccount
    Public Property Id As Integer
    Public Property Name As String
    Public Property Street As String
    Public Property Housenumber As String
    Public Property Busnumber As String
    Public Property PostalCodeID As Nullable(Of Integer)
    Public Property DateSalesAgreement As Nullable(Of Date)
    Public Property DateDeedOfSale As Nullable(Of Date)
    Public Property OwnerPercentage As Nullable(Of Integer)
    Public Property OwnerTypeId As Nullable(Of Integer)
    Public Property Salutation As String
    Public Property VATnumber As String
    Public Property CompanyName As String
    Public Property StartDateConstruction As Nullable(Of Date)
    Public Property ExecutionDays As Nullable(Of Integer)
    Public Property BankAccountNumber As String
    Public Property InvoiceStreet As String
    Public Property InvoiceHousenumber As String
    Public Property InvoiceBusnumber As String
    Public Property InvoicePostalCodeId As Nullable(Of Integer)
    Public Property InvoiceAddress As Nullable(Of Boolean)
    Public Property DeliveryDate As Nullable(Of Date)
    Public Property DeliveryDoc As String
    Public Property DeliveryDateDef As Nullable(Of Date)
    Public Property InvoiceExtra As String
    Public Property DeedOfSaleExpDate As Nullable(Of Date)

    Public Overridable Property ClientContacts As ICollection(Of ClientContacts) = New HashSet(Of ClientContacts)
    Public Overridable Property Units As ICollection(Of Units) = New HashSet(Of Units)
    Public Overridable Property PostalCode As PostalCode
    Public Overridable Property ClientOwnerType As ClientOwnerType
    Public Overridable Property ClientGift As ICollection(Of ClientGift) = New HashSet(Of ClientGift)
    Public Overridable Property InvoicePostalCode As PostalCode
    Public Overridable Property ProjectDocs As ICollection(Of ProjectDocs) = New HashSet(Of ProjectDocs)
    Public Overridable Property ChangeOrder As ICollection(Of ChangeOrder) = New HashSet(Of ChangeOrder)
    Public Overridable Property ClientPOA As ICollection(Of ClientPOA) = New HashSet(Of ClientPOA)
    Public Overridable Property UtilityPercentage As ICollection(Of UtilityPercentage) = New HashSet(Of UtilityPercentage)

End Class
