'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientContacts
    Public Property Id As Integer
    Public Property Name As String
    Public Property Street As String
    Public Property Housenumber As String
    Public Property Busnumber As String
    Public Property PostalCodeID As Nullable(Of Integer)
    Public Property Phone As String
    Public Property Cellphone As String
    Public Property Email As String
    Public Property IsCoOwner As Boolean
    Public Property CoOwnerPercentage As Nullable(Of Decimal)
    Public Property CoOwnerTypeID As Nullable(Of Integer)
    Public Property ClientAccountID As Integer
    Public Property Forename As String
    Public Property Salutation As String
    Public Property CompanyName As String
    Public Property VATnumber As String
    Public Property InvoiceStreet As String
    Public Property InvoiceHousenumber As String
    Public Property InvoiceBusnumber As String
    Public Property InvoicePostalCodeID As Nullable(Of Integer)
    Public Property InvoiceAddress As Nullable(Of Boolean)

    Public Overridable Property ClientAccount As ClientAccount
    Public Overridable Property ClientOwnerType As ClientOwnerType
    Public Overridable Property PostalCode As PostalCode
    Public Overridable Property InvoicePostalCode As PostalCode

End Class
