'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientPOA
    Public Property Id As Integer
    Public Property ClientAccountId As Integer
    Public Property Description As String

    Public Overridable Property ClientAccount As ClientAccount
    Public Overridable Property Activity As ICollection(Of Activity) = New HashSet(Of Activity)

End Class
