'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CompanyDepartments
    Public Property DepartmentId As Integer
    Public Property Naam As String
    Public Property Straat As String
    Public Property Huisnummer As String
    Public Property Bus As String
    Public Property PostcodeId As Nullable(Of Integer)
    Public Property Telefoon As String
    Public Property GSM As String
    Public Property Email As String
    Public Property CompanyId As Integer

    Public Overridable Property CompanyContacts As ICollection(Of CompanyContacts) = New HashSet(Of CompanyContacts)
    Public Overridable Property CompanyInfo As CompanyInfo
    Public Overridable Property PostalCode As PostalCode

End Class
