'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CompanyContacts
    Public Property ContactID As Integer
    Public Property CompanyID As Integer
    Public Property ContactNaam As String
    Public Property ContactVoornaam As String
    Public Property Aanspreking As String
    Public Property Functie As String
    Public Property Telefoon As String
    Public Property GSM As String
    Public Property Fax As String
    Public Property Email As String
    Public Property DepartmentID As Nullable(Of Integer)

    Public Overridable Property CompanyDepartments As CompanyDepartments
    Public Overridable Property CompanyInfo As CompanyInfo

End Class
