'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contract
    Public Property ID As Integer
    Public Property ProjectID As Integer
    Public Property CompanyID As Integer
    Public Property VatPercentage As Nullable(Of Decimal)
    Public Property PaymentTerm As Nullable(Of Decimal)
    Public Property CashDiscountPercentage As Nullable(Of Decimal)
    Public Property CashDiscountPaymentTerm As Nullable(Of Decimal)
    Public Property CashDiscount As Boolean
    Public Property GuaranteeType As Nullable(Of Integer)
    Public Property GuaranteePercentage As Nullable(Of Decimal)
    Public Property ContractSigned As Nullable(Of Boolean)

    Public Overridable Property CompanyInfo As CompanyInfo
    Public Overridable Property Project As Project
    Public Overridable Property ContractActivity As ICollection(Of ContractActivity) = New HashSet(Of ContractActivity)
    Public Overridable Property IncommingInvoices As ICollection(Of IncommingInvoices) = New HashSet(Of IncommingInvoices)
    Public Overridable Property UtilityPercentage As ICollection(Of UtilityPercentage) = New HashSet(Of UtilityPercentage)

End Class
