'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class copropmEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=copropmEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Permission() As DbSet(Of Permission)
    Public Overridable Property PermissionPerUser() As DbSet(Of PermissionPerUser)
    Public Overridable Property Users() As DbSet(Of Users)
    Public Overridable Property Country() As DbSet(Of Country)
    Public Overridable Property PostalCode() As DbSet(Of PostalCode)
    Public Overridable Property Provincie() As DbSet(Of Provincie)
    Public Overridable Property CompanyInfo() As DbSet(Of CompanyInfo)
    Public Overridable Property WheaterStations() As DbSet(Of WheaterStations)
    Public Overridable Property Activity() As DbSet(Of Activity)
    Public Overridable Property ActivityGroup() As DbSet(Of ActivityGroup)
    Public Overridable Property CompanyContacts() As DbSet(Of CompanyContacts)
    Public Overridable Property CompanyDepartments() As DbSet(Of CompanyDepartments)
    Public Overridable Property Project() As DbSet(Of Project)
    Public Overridable Property ProjectStatus() As DbSet(Of ProjectStatus)
    Public Overridable Property ProjectNews() As DbSet(Of ProjectNews)
    Public Overridable Property AspNetRoles() As DbSet(Of AspNetRoles)
    Public Overridable Property AspNetUsers() As DbSet(Of AspNetUsers)
    Public Overridable Property UnitGroupTypes() As DbSet(Of UnitGroupTypes)
    Public Overridable Property Units() As DbSet(Of Units)
    Public Overridable Property UnitTypes() As DbSet(Of UnitTypes)
    Public Overridable Property ProjectLevels() As DbSet(Of ProjectLevels)
    Public Overridable Property ClientAccount() As DbSet(Of ClientAccount)
    Public Overridable Property ClientContacts() As DbSet(Of ClientContacts)
    Public Overridable Property ClientOwnerType() As DbSet(Of ClientOwnerType)
    Public Overridable Property ProjectPictures() As DbSet(Of ProjectPictures)
    Public Overridable Property ClientGift() As DbSet(Of ClientGift)
    Public Overridable Property BadWeatherDays() As DbSet(Of BadWeatherDays)
    Public Overridable Property VacationDays() As DbSet(Of VacationDays)
    Public Overridable Property ProjectSalesSettings() As DbSet(Of ProjectSalesSettings)
    Public Overridable Property UnitRooms() As DbSet(Of UnitRooms)
    Public Overridable Property ProjectDocs() As DbSet(Of ProjectDocs)
    Public Overridable Property InvoicingPaymentGroup() As DbSet(Of InvoicingPaymentGroup)
    Public Overridable Property Invoices() As DbSet(Of Invoices)
    Public Overridable Property InvoicesDetails() As DbSet(Of InvoicesDetails)
    Public Overridable Property ProjectBudget() As DbSet(Of ProjectBudget)
    Public Overridable Property ChangeOrder() As DbSet(Of ChangeOrder)
    Public Overridable Property InsuranceCompanies() As DbSet(Of InsuranceCompanies)
    Public Overridable Property Contract() As DbSet(Of Contract)
    Public Overridable Property ContractActivity() As DbSet(Of ContractActivity)
    Public Overridable Property Insurances() As DbSet(Of Insurances)
    Public Overridable Property ChangeOrderDetail() As DbSet(Of ChangeOrderDetail)
    Public Overridable Property ClientPOA() As DbSet(Of ClientPOA)
    Public Overridable Property InvoicingPaymentStages() As DbSet(Of InvoicingPaymentStages)
    Public Overridable Property UnitConstructionValue() As DbSet(Of UnitConstructionValue)
    Public Overridable Property IncommingInvoiceDetail() As DbSet(Of IncommingInvoiceDetail)
    Public Overridable Property IncommingInvoices() As DbSet(Of IncommingInvoices)
    Public Overridable Property UtilityPercentage() As DbSet(Of UtilityPercentage)
    Public Overridable Property LogList() As DbSet(Of LogList)

End Class
