'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IncommingInvoiceDetail
    Public Property ID As Integer
    Public Property IncommingInvoiceID As Integer
    Public Property Description As String
    Public Property Price As Nullable(Of Decimal)
    Public Property ContractActID As Nullable(Of Integer)
    Public Property Type As Decimal
    Public Property ChangeOrderID As Nullable(Of Integer)
    Public Property ActID As Nullable(Of Integer)

    Public Overridable Property Activity As Activity
    Public Overridable Property ChangeOrder As ChangeOrder
    Public Overridable Property ContractActivity As ContractActivity
    Public Overridable Property IncommingInvoices As IncommingInvoices
    Public Overridable Property UtilityPercentage As ICollection(Of UtilityPercentage) = New HashSet(Of UtilityPercentage)

End Class
