'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvoicingPaymentGroup
    Public Property Id As Integer
    Public Property Name As String
    Public Property ProjectId As Integer
    Public Property VatPercentage As Nullable(Of Decimal)

    Public Overridable Property Project As Project
    Public Overridable Property Units As ICollection(Of Units) = New HashSet(Of Units)
    Public Overridable Property InvoicingPaymentStages As ICollection(Of InvoicingPaymentStages) = New HashSet(Of InvoicingPaymentStages)
    Public Overridable Property UnitConstructionValue As ICollection(Of UnitConstructionValue) = New HashSet(Of UnitConstructionValue)

End Class
