'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvoicingPaymentStages
    Public Property Id As Integer
    Public Property Name As String
    Public Property Percentage As Decimal
    Public Property Invoicable As Nullable(Of Boolean)
    Public Property GroupId As Integer
    Public Property DocId As Nullable(Of Integer)
    Public Property VatPercentage As Decimal

    Public Overridable Property InvoicesDetails As ICollection(Of InvoicesDetails) = New HashSet(Of InvoicesDetails)
    Public Overridable Property InvoicingPaymentGroup As InvoicingPaymentGroup
    Public Overridable Property ProjectDocs As ProjectDocs

End Class
