'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Invoices
    Public Property Id As Integer
    Public Property Filename As String
    Public Property [Date] As Date
    Public Property ClientId As Integer
    Public Property ClientType As Integer
    Public Property PublicId As String
    Public Property ExpirationDate As Nullable(Of Date)
    Public Property VatNumber As String
    Public Property ClientName As String
    Public Property Adress As String
    Public Property PostalCodeID As Nullable(Of Integer)
    Public Property BankAccount As String
    Public Property ExtraInfo As String
    Public Property Text As String
    Public Property DetailText As String
    Public Property CompanyID As Nullable(Of Integer)

    Public Overridable Property InvoicesDetails As ICollection(Of InvoicesDetails) = New HashSet(Of InvoicesDetails)
    Public Overridable Property PostalCode As PostalCode
    Public Overridable Property Units As ICollection(Of Units) = New HashSet(Of Units)

End Class
