'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvoicesDetails
    Public Property Id As Integer
    Public Property InvoiceId As Integer
    Public Property PaymentStageId As Nullable(Of Integer)
    Public Property UnitId As Nullable(Of Integer)
    Public Property ChangeOrderDetailId As Nullable(Of Integer)
    Public Property ConstructionValueId As Nullable(Of Integer)
    Public Property Text As String
    Public Property VatPercentage As Nullable(Of Decimal)
    Public Property Price As Nullable(Of Decimal)
    Public Property GroupName As String
    Public Property UtilityCost As Nullable(Of Boolean)

    Public Overridable Property Invoices As Invoices
    Public Overridable Property Units As Units
    Public Overridable Property ChangeOrderDetail As ChangeOrderDetail
    Public Overridable Property InvoicingPaymentStages As InvoicingPaymentStages

End Class
