'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Permission
    Public Property PermissionID As Integer
    Public Property PermissionName As String

    Public Overridable Property PermissionPerUser As ICollection(Of PermissionPerUser) = New HashSet(Of PermissionPerUser)

End Class
