'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PermissionPerUser
    Public Property PermissionID As Integer
    Public Property UserID As Integer
    Public Property Permission As Nullable(Of Integer)

    Public Overridable Property Permissions As Permission
    Public Overridable Property Users As Users

End Class
