'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PostalCode
    Public Property PostcodeID As Integer
    Public Property Postcode As String
    Public Property Gemeente As String
    Public Property CountryID As Nullable(Of Integer)
    Public Property ProvincieID As Nullable(Of Integer)

    Public Overridable Property Country As Country
    Public Overridable Property Provincie As Provincie
    Public Overridable Property CompanyInfo As ICollection(Of CompanyInfo) = New HashSet(Of CompanyInfo)
    Public Overridable Property CompanyDepartments As ICollection(Of CompanyDepartments) = New HashSet(Of CompanyDepartments)
    Public Overridable Property Project As ICollection(Of Project) = New HashSet(Of Project)
    Public Overridable Property ClientAccount As ICollection(Of ClientAccount) = New HashSet(Of ClientAccount)
    Public Overridable Property ClientContacts As ICollection(Of ClientContacts) = New HashSet(Of ClientContacts)
    Public Overridable Property ClientAccount1 As ICollection(Of ClientAccount) = New HashSet(Of ClientAccount)
    Public Overridable Property ClientContacts1 As ICollection(Of ClientContacts) = New HashSet(Of ClientContacts)
    Public Overridable Property InsuranceCompanies As ICollection(Of InsuranceCompanies) = New HashSet(Of InsuranceCompanies)
    Public Overridable Property Invoices As ICollection(Of Invoices) = New HashSet(Of Invoices)

End Class
