'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectBudget
    Public Property ID As Integer
    Public Property ProjectID As Integer
    Public Property ActivityID As Integer
    Public Property Price As Decimal

    Public Overridable Property Activity As Activity
    Public Overridable Property Project As Project

End Class
