'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectSalesSettings
    Public Property Id As Integer
    Public Property Projectid As Integer
    Public Property VATPercentage As Nullable(Of Decimal)
    Public Property RegistrationPercentage As Nullable(Of Decimal)
    Public Property MixedVATRegistration As Nullable(Of Boolean)
    Public Property ConnectionFees As Nullable(Of Decimal)
    Public Property BaseCertificateCost As Nullable(Of Decimal)
    Public Property FixedCertificateCost As Nullable(Of Decimal)
    Public Property MortageRegistrationCost As Nullable(Of Decimal)
    Public Property BankAccountNumber As String
    Public Property SaleVisible As Nullable(Of Boolean)
    Public Property RegistrationType As Nullable(Of Integer)
    Public Property SurveyorCost As Nullable(Of Decimal)
    Public Property ParcelCost As Nullable(Of Decimal)

    Public Overridable Property Project As Project

End Class
