'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectDocs
    Public Property Id As Integer
    Public Property ProjectId As Integer
    Public Property Name As String
    Public Property Filename As String
    Public Property SortOrder As Integer
    Public Property Type As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property ClientAccountId As Nullable(Of Integer)

    Public Overridable Property Project As Project
    Public Overridable Property ClientAccount As ClientAccount
    Public Overridable Property InvoicingPaymentStages As ICollection(Of InvoicingPaymentStages) = New HashSet(Of InvoicingPaymentStages)

End Class
