'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectLevels
    Public Property Id As Integer
    Public Property Level As String
    Public Property ProjectId As Integer
    Public Property Number As Nullable(Of Integer)

    Public Overridable Property Project As Project
    Public Overridable Property Units As ICollection(Of Units) = New HashSet(Of Units)

End Class
