'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Project
    Public Property ProjectID As Integer
    Public Property ProjectName As String
    Public Property PostalCodeID As Nullable(Of Integer)
    Public Property Street As String
    Public Property Number As String
    Public Property StatusID As Nullable(Of Integer)
    Public Property CommercialTitleNL As String
    Public Property CommercialTextNL As String
    Public Property ConstructionYear As Nullable(Of Date)
    Public Property DeliveryDate As Nullable(Of Date)
    Public Property StartDateConstruction As Nullable(Of Date)
    Public Property DeveloperID As Nullable(Of Integer)
    Public Property ExecutionDays As Nullable(Of Integer)
    Public Property WheaterStationID As Nullable(Of Integer)
    Public Property DefaultPictureId As Nullable(Of Integer)
    Public Property EngineerID As Nullable(Of Integer)
    Public Property SecurityCoordinatorID As Nullable(Of Integer)
    Public Property EpbReporterID As Nullable(Of Integer)
    Public Property ArchitectID As Nullable(Of Integer)
    Public Property FacebookAlbumID As Nullable(Of Decimal)
    Public Property Slug As String
    Public Property BuilderID As Nullable(Of Integer)
    Public Property AspNetUserID As String
    Public Property TotalLandShare As Nullable(Of Decimal)
    Public Property FacebookPlaceId As String
    Public Property ProjectFolder As String
    Public Property DeliveryDateDef As Nullable(Of Date)
    Public Property UploadToFacebook As Nullable(Of Boolean)
    Public Property DocPID As Nullable(Of Boolean)
    Public Property DocElectricalInspection As Nullable(Of Boolean)
    Public Property DocWaterInspection As Nullable(Of Boolean)
    Public Property DocSewerInspection As Nullable(Of Boolean)
    Public Property DocFireInspection As Nullable(Of Boolean)
    Public Property DocDelivery As Nullable(Of Boolean)
    Public Property DocDefDelivery As Nullable(Of Boolean)
    Public Property ProjectType As Integer

    Public Overridable Property Developer As CompanyInfo
    Public Overridable Property PostalCode As PostalCode
    Public Overridable Property ProjectStatus As ProjectStatus
    Public Overridable Property WheaterStations As WheaterStations
    Public Overridable Property Engineer As CompanyInfo
    Public Overridable Property SecurityCoordinator As CompanyInfo
    Public Overridable Property EpbReporter As CompanyInfo
    Public Overridable Property Architect As CompanyInfo
    Public Overridable Property ProjectNews As ICollection(Of ProjectNews) = New HashSet(Of ProjectNews)
    Public Overridable Property Builder As CompanyInfo
    Public Overridable Property AspNetUsers As AspNetUsers
    Public Overridable Property Units As ICollection(Of Units) = New HashSet(Of Units)
    Public Overridable Property ProjectLevels As ICollection(Of ProjectLevels) = New HashSet(Of ProjectLevels)
    Public Overridable Property DefaultPicture As ProjectPictures
    Public Overridable Property ProjectPictures As ICollection(Of ProjectPictures) = New HashSet(Of ProjectPictures)
    Public Overridable Property VacationDays As ICollection(Of VacationDays) = New HashSet(Of VacationDays)
    Public Overridable Property ProjectSalesSettings As ICollection(Of ProjectSalesSettings) = New HashSet(Of ProjectSalesSettings)
    Public Overridable Property ProjectDocs As ICollection(Of ProjectDocs) = New HashSet(Of ProjectDocs)
    Public Overridable Property InvoicingPaymentGroup As ICollection(Of InvoicingPaymentGroup) = New HashSet(Of InvoicingPaymentGroup)
    Public Overridable Property ProjectBudget As ICollection(Of ProjectBudget) = New HashSet(Of ProjectBudget)
    Public Overridable Property Contract As ICollection(Of Contract) = New HashSet(Of Contract)
    Public Overridable Property IncommingInvoices As ICollection(Of IncommingInvoices) = New HashSet(Of IncommingInvoices)

End Class
