'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnitRooms
    Public Property RoomId As Integer
    Public Property UnitId As Integer
    Public Property Type As Integer
    Public Property Number As Integer
    Public Property Surface As Nullable(Of Decimal)
    Public Property Remark As String

    Public Overridable Property Units As Units

End Class
