'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnitTypes
    Public Property ID As Integer
    Public Property Name As String
    Public Property GroupID As Integer
    Public Property Shortcode As String
    Public Property Selectable As Nullable(Of Boolean)

    Public Overridable Property UnitGroupTypes As UnitGroupTypes
    Public Overridable Property Units As ICollection(Of Units) = New HashSet(Of Units)

End Class
