'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnitFinishingOption
    Public Property Id As Integer
    Public Property UnitId As Integer
    Public Property Name As String
    Public Property SortOrder As Integer
    Public Property IsDefault As Boolean

    Public Overridable Property Units As Units
    Public Overridable Property UnitConstructionValues As ICollection(Of UnitConstructionValue) = New HashSet(Of UnitConstructionValue)

End Class
