'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnitConstructionValue
    Public Property Id As Integer
    Public Property Value As Nullable(Of Decimal)
    Public Property ValueSold As Nullable(Of Decimal)
    Public Property Description As String
    Public Property PaymentGroupId As Nullable(Of Integer)
    Public Property UnitId As Integer

    Public Overridable Property InvoicingPaymentGroup As InvoicingPaymentGroup
    Public Overridable Property Units As Units

End Class
