'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Users
    Public Property UserID As String
    Public Property Password As String
    Public Property Type As Nullable(Of Decimal)
    Public Property Voornaam As String
    Public Property Familienaam As String
    Public Property Functie As String
    Public Property GSM As String
    Public Property Initiaal As String
    Public Property Email As String
    Public Property ID As Integer

    Public Overridable Property PermissionPerUser As ICollection(Of PermissionPerUser) = New HashSet(Of PermissionPerUser)

End Class
