'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VacationDays
    Public Property Id As Integer
    Public Property VacationDay As Date
    Public Property ProjectId As Nullable(Of Integer)

    Public Overridable Property Project As Project

End Class
