'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WheaterStations
    Public Property ID As Integer
    Public Property Name As String
    Public Property Visible As Nullable(Of Boolean)
    Public Property latitude As Nullable(Of Decimal)
    Public Property longitude As Nullable(Of Decimal)

    Public Overridable Property Project As ICollection(Of Project) = New HashSet(Of Project)
    Public Overridable Property BadWeatherDays As ICollection(Of BadWeatherDays) = New HashSet(Of BadWeatherDays)

End Class
