'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.groupln.be/Uploads/")>  _
        Public ReadOnly Property ImageWebURL() As String
            Get
                Return CType(Me("ImageWebURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EAAIimmlGFwkBAD1Q4LYdDf63Es0mIJ1JVNae1dB4DattoX9bEO1GMRvBZBaFwVEmrcirC4dVhYLjkZA1"& _ 
            "pJnGDQ4mHdaHupApwSOzUBiBCTZBQ1LUMRFY6wLOmFMeZAGMeW802KZCP2YqjqFuybWqgZAfMIp35hp8"& _ 
            "UZD")>  _
        Public ReadOnly Property FacebookAccessTokenCopro() As String
            Get
                Return CType(Me("FacebookAccessTokenCopro"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600996539930377|Vu7n9p-HKTVLNup58TGDEQY3oos")>  _
        Public ReadOnly Property FacebookAppTokenCopro() As String
            Get
                Return CType(Me("FacebookAppTokenCopro"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("208486209193590")>  _
        Public ReadOnly Property FacebookIDCopro() As String
            Get
                Return CType(Me("FacebookIDCopro"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600996539930377")>  _
        Public ReadOnly Property FacebookAppId() As String
            Get
                Return CType(Me("FacebookAppId"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\04 - Klanten\02 - Opleveringsverslagen\")>  _
        Public ReadOnly Property DeliveryDocLocalURL() As String
            Get
                Return CType(Me("DeliveryDocLocalURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server.groupln.local\WEBSITES\Copro\Uploads\Pictures\")>  _
        Public ReadOnly Property ImageLocalURL() As String
            Get
                Return CType(Me("ImageLocalURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server.groupln.local\WEBSITES\Copro\Uploads\Plans\")>  _
        Public ReadOnly Property PlanLocalURL() As String
            Get
                Return CType(Me("PlanLocalURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\server.groupln.local\WEBSITES\Copro\Uploads\Docs\")>  _
        Public ReadOnly Property DocLocalURL() As String
            Get
                Return CType(Me("DocLocalURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\nasarchive.groupln.local\data\BCO\Algemeen\Documenten\Standaard\template.docx")>  _
        Public ReadOnly Property TemplateInvoiceBCO() As String
            Get
                Return CType(Me("TemplateInvoiceBCO"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Klaverdries 53")>  _
        Public ReadOnly Property CompanyStreetNr() As String
            Get
                Return CType(Me("CompanyStreetNr"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9031 Drongen")>  _
        Public ReadOnly Property CompanyPostalcode() As String
            Get
                Return CType(Me("CompanyPostalcode"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info@bouwenconstructie.be")>  _
        Public ReadOnly Property CompanyEmail() As String
            Get
                Return CType(Me("CompanyEmail"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("www.bouwenconstructie.be")>  _
        Public ReadOnly Property CompanyWWW() As String
            Get
                Return CType(Me("CompanyWWW"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BCO BV")>  _
        Public ReadOnly Property CompanyName() As String
            Get
                Return CType(Me("CompanyName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BE 0464.670.778")>  _
        Public ReadOnly Property CompanyVAT() As String
            Get
                Return CType(Me("CompanyVAT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RPR GENT")>  _
        Public ReadOnly Property CompanyRPR() As String
            Get
                Return CType(Me("CompanyRPR"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BE68 0015 1882 9434")>  _
        Public ReadOnly Property CompanyBankaccount() As String
            Get
                Return CType(Me("CompanyBankaccount"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T +32 (0)9 216 49 50")>  _
        Public ReadOnly Property CompanyPhone() As String
            Get
                Return CType(Me("CompanyPhone"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("F +32 (0)9 223 73 00")>  _
        Public ReadOnly Property CompanyFax() As String
            Get
                Return CType(Me("CompanyFax"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\nasarchive.groupln.local\data\Group LN\Algemeen\Documenten\Standaard\Facturen\t"& _ 
            "emplate.docx")>  _
        Public ReadOnly Property TemplateInvoiceGroupLN() As String
            Get
                Return CType(Me("TemplateInvoiceGroupLN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BCO\Boekhouding\Facturatie\")>  _
        Public ReadOnly Property InvoiceFtpURL() As String
            Get
                Return CType(Me("InvoiceFtpURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.groupln.be/Uploads/")>  _
        Public ReadOnly Property PlanWebURL() As String
            Get
                Return CType(Me("PlanWebURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.groupln.be/Uploads/")>  _
        Public ReadOnly Property DocWebURL() As String
            Get
                Return CType(Me("DocWebURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/BCO/Boekhouding/Facturatie/")>  _
        Public ReadOnly Property InvoiceURLFTP() As String
            Get
                Return CType(Me("InvoiceURLFTP"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/BCO/Boekhouding/Facturatie/")>  _
        Public ReadOnly Property InvoiceURL() As String
            Get
                Return CType(Me("InvoiceURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/Group LN/Boekhouding/Facturatie/")>  _
        Public ReadOnly Property InvoiceURLGroupLN() As String
            Get
                Return CType(Me("InvoiceURLGroupLN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\TFS\CPM\Temp\")>  _
        Public ReadOnly Property localTempPath() As String
            Get
                Return CType(Me("localTempPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("79.132.239.221")>  _
        Public ReadOnly Property FTPHost() As String
            Get
                Return CType(Me("FTPHost"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("latni")>  _
        Public ReadOnly Property FTPUser() As String
            Get
                Return CType(Me("FTPUser"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("840683Pas")>  _
        Public ReadOnly Property FTPPassword() As String
            Get
                Return CType(Me("FTPPassword"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1433")>  _
        Public ReadOnly Property FTPPort() As String
            Get
                Return CType(Me("FTPPort"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CPM.My.MySettings
            Get
                Return Global.CPM.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
