<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GroupLN.MarketData.Worker</RootNamespace>
    <UserSecretsId>groupln-marketdata-worker</UserSecretsId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GroupLN.MarketData.Core\GroupLN.MarketData.Core.csproj" />
    <ProjectReference Include="..\GroupLN.MarketData.Infrastructure\GroupLN.MarketData.Infrastructure.csproj" />
    <ProjectReference Include="..\GroupLN.MarketData.Persistence\GroupLN.MarketData.Persistence.csproj" />
  </ItemGroup>
</Project>
